### ISSUE TITLE
Error Running xView Example

### ISSUE THREAD

**Issue by satyajitghana** [azavea/raster-vision#1063]
I am trying to run the xView Example

I've preprocessed the dataset using the notebook provided, and verified that my folders have the right data, now i am trying to run below,

```bash
export RAW_URI='/opt/data/xView/'
export PROCESSED_URI='/opt/data/xView-Processed'
export ROOT_URI='/opt/data/xView-Output'

echo RAW_URI=$RAW_URI
echo PROCESSED_URI=$PROCESSED_URI
echo ROOT_URI=$ROOT_URI

rastervision run local rastervision_pytorch_backend/rastervision/pytorch_backend/examples/object_detection/xview.py \
    -a raw_uri $RAW_URI -a processed_uri $PROCESSED_URI -a root_uri $ROOT_URI \
    -a test False --splits 8
```

which results in 

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 248, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 170, in run
    cfgs = get_configs(cfg_module, runner, args)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 74, in get_configs
    cfgs = _get_configs(runner, **args)
  File "rastervision_pytorch_backend/rastervision/pytorch_backend/examples/object_detection/xview.py", line 67, in get_config
    test_mode=test)
  File "pydantic/main.py", line 274, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PyTorchObjectDetectionConfig
data
  field required (type=value_error.missing)
```

**Comment by satyajitghana** [comment]
I guess the docs need to be updated, its working on  `v0.12`

**Comment by AdeelH** [comment]
You are right. That example got broken by recent changes. As a quick fix, you can change the lines 
https://github.com/azavea/raster-vision/blob/master/rastervision_pytorch_backend/rastervision/pytorch_backend/examples/object_detection/xview.py#L57-L67

to:
```python3
    backend = PyTorchObjectDetectionConfig(
        data=ObjectDetectionImageDataConfig(),
        model=ObjectDetectionModelConfig(backbone=Backbone.resnet50),
        solver=SolverConfig(
            lr=1e-4,
            num_epochs=10,
            test_num_epochs=2,
            batch_sz=16,
            one_cycle=True),
        log_tensorboard=True,
        run_tensorboard=False,
        test_mode=test)
```

Note: the only change is the addition of `data=ObjectDetectionImageDataConfig()`.

**Comment by AdeelH** [comment]
`xview.py` should be working on `master` now.
