### ISSUE TITLE
Problem using pretrained weights, "init_weights"

### ISSUE THREAD

**Issue by greenhawktobias** [azavea/raster-vision#1120]
Hi,
I am trying to use initial weights to benefit from previously trained model.

Using the master branch of RV
Code below:
```
 backend = PyTorchSemanticSegmentationConfig(
        data=SemanticSegmentationImageDataConfig(img_channels=len(channel_order), img_sz=img_sz),
        model=SemanticSegmentationModelConfig(backbone=Backbone.resnet50,init_weights='/opt/src/code/model.pth'),
```

**I get RuntimeError: Error(s) in loading state_dict for DeepLabV3:
        Missing key(s) in state_dict: "backbone.conv1.1.0.weight", "backbone.conv1.1.1.weight".
        Unexpected key(s) in state_dict: "backbone.conv1.weight".**

pipeline-config.json and model,pth are keept in the code folder mounted in docker.

Should I add something in my code?

```
Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /opt/data/torch-cache/hub/checkpoints/resnet50-19c8e357.pth
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 97.8M/97.8M [00:30<00:00, 3.31MB/s]Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 248, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 240, in run_command
    runner=runner)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 217, in _run_command
    command_fn()
  File "/opt/src/rastervision_core/rastervision/core/rv_pipeline/rv_pipeline.py", line 115, in train
    backend.train(source_bundle_uri=self.config.source_bundle_uri)
  File "/opt/src/rastervision_pytorch_backend/rastervision/pytorch_backend/pytorch_learner_backend.py", line 74, in train
    learner = self.learner_cfg.build(self.tmp_dir, training=True)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/semantic_segmentation_learner_config.py", line 157, in build
    training=training)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner.py", line 155, in __init__
    self.setup_model(model_def_path=model_def_path)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner.py", line 275, in setup_model
    self.load_init_weights()
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner.py", line 1085, in load_init_weights
    torch.load(weights_path, map_location=self.device))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DeepLabV3:
        Missing key(s) in state_dict: "backbone.conv1.1.0.weight", "backbone.conv1.1.1.weight".
        Unexpected key(s) in state_dict: "backbone.conv1.weight".
/opt/data/output/Makefile:12: recipe for target '2' failed
make: *** [2] Error 1
root@3a70516cd0f9:/opt/src#
```

**Comment by AdeelH** [comment]
Was the pretrained model created using Raster Vision? Does it take in 3 channels or more than 3 channels? How many channels are you using in your current model?

**Comment by greenhawktobias** [comment]
I tried now with a RV 4 channel model as pretrained to use on a current 4 channel model. It works now!
Is it possible to use other model weights (not RV) with more or less channels than a current model?

**Comment by AdeelH** [comment]
>Is it possible to use other model weights (not RV) with more or less channels than a current model?

By default, RV uses ImageNet pretrained weights and is able to use them even if channels != 3. 

If you want to use weights that have been trained on something other than ImageNet and modify it to use channels != 3, that is currently not supported. But it seems like a useful feature to have. Feel free to create a new issue about it.
