### ISSUE TITLE
Rastervision run_command error

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1164]
Rastervision "run_command" command generate makefile and json file but exit with following error.

i'm running cowc_potsdam.py file. and using python 3.6.2 and rastervision 0.13.

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\rv_0.13\Scripts\rastervision.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\desktop\rv_0.13\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\desktop\rv_0.13\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\desktop\rv_0.13\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\desktop\rv_0.13\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\desktop\rv_0.13\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\administrator\desktop\rv_0.13\lib\site-packages\rastervision\pipeline\cli.py", line 175, in run
    pipeline_run_name)
  File "c:\users\administrator\desktop\rv_0.13\lib\site-packages\rastervision\pipeline\cli.py", line 129, in _run_pipeline
    pipeline_run_name=pipeline_run_name)
  File "c:\users\administrator\desktop\rv_0.13\lib\site-packages\rastervision\pipeline\runner\local_runner.py", line 71, in run
    process = Popen(['make', '-j', '-f', makefile_path])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 991, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by AdeelH** [comment]
Raster Vision is not guaranteed to run natively on Windows. I would recommend running it inside a docker container if you are on Windows.

You can get RV docker images here: https://quay.io/repository/azavea/raster-vision?tab=tags
