### ISSUE TITLE
rastervision train command error 

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1165]
i'm running cowc_postdam.py file and running train command from makefile.

command : "python -m rastervision.pipeline.cli run_command C:\Users\Administrator\Downloads\pipeline-config.json train"

The training data is generated by chip command.

by running train command I got following error. i'm using python 3.6.2 and rastervision 0.13
  
Running train command...
2021-06-04 09:59:13:rastervision.pytorch_learner.learner: INFO - Physical CPUs: 2
2021-06-04 09:59:13:rastervision.pytorch_learner.learner: INFO - Logical CPUs: 2
2021-06-04 09:59:13:rastervision.pytorch_learner.learner: INFO - Total memory:  8.00 GB
2021-06-04 09:59:13:rastervision.pytorch_learner.learner: INFO - Size of /opt/data volume:  70.00 GB
2021-06-04 09:59:13:rastervision.pytorch_learner.learner: INFO - Python version: 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
2021-06-04 09:59:13:rastervision.pytorch_learner.learner: INFO - nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:41:42_Pacific_Daylight_Time_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.
2021-06-04 09:59:13:rastervision.pytorch_learner.learner: INFO -
2021-06-04 09:59:13:rastervision.pytorch_learner.learner: INFO - Devices:
2021-06-04 09:59:13:rastervision.pytorch_learner.learner: INFO - PyTorch version: 1.7.0+cpu
2021-06-04 09:59:13:rastervision.pytorch_learner.learner: INFO - CUDA available: False
2021-06-04 09:59:13:rastervision.pytorch_learner.learner: INFO - CUDA version: None
2021-06-04 09:59:13:rastervision.pytorch_learner.learner: INFO - CUDNN version: None
2021-06-04 09:59:13:rastervision.pytorch_learner.learner: INFO - Number of CUDA devices: 0
2021-06-04 09:59:14:rastervision.pytorch_learner.learner: INFO - model=ObjectDetectionModelConfig(backbone=<Backbone.resnet18: 'resnet18'>, pretrained=True, init_weights=None, external_def=None, type_hint='object_detection_model') solver=SolverConfig(lr=0.0001, num_epochs=10, test_num_epochs=2, test_batch_sz=4, overfit_num_steps=1, sync_interval=1, batch_sz=16, one_cycle=True, multi_stage=[], class_loss_weights=None, ignore_last_class=False, external_loss_def=None, type_hint='solver') data=ObjectDetectionImageDataConfig(class_names=['vehicle'], class_colors=[[115, 12, 41]], img_sz=300, train_sz=None, num_workers=4, augmentors=['RandomRotate90', 'HorizontalFlip', 'VerticalFlip'], base_transform=None, aug_transform=None, plot_options=PlotOptions(transform=None, type_hint='plot_options'), preview_batch_limit=None, type_hint='object_detection_image_data', data_format=<ObjectDetectionDataFormat.coco: 'coco'>, uri='C:\\Users\\Administrator\\Downloads\\chip', group_uris=None, group_train_sz=None, group_train_sz_rel=None) predict_mode=False test_mode=False overfit_mode=False eval_train=False save_model_bundle=True log_tensorboard=False run_tensorboard=False output_uri='C:\\Users\\Administrator\\Downloads\\train' type_hint='object_detection_learner'
2021-06-04 09:59:14:rastervision.pytorch_learner.learner: INFO - Using device: cpu
2021-06-04 09:59:32:rastervision.pytorch_learner.learner: INFO - train_ds: 6726 items
2021-06-04 09:59:32:rastervision.pytorch_learner.learner: INFO - valid_ds: 2232 items
2021-06-04 09:59:32:rastervision.pytorch_learner.learner: INFO - test_ds: 2232 items
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\rv_0.13\lib\site-packages\rastervision\pipeline\cli.py", line 248, in <module>
    main()
  File "C:\Users\Administrator\Desktop\rv_0.13\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\rv_0.13\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\Desktop\rv_0.13\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\Desktop\rv_0.13\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\Desktop\rv_0.13\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\rv_0.13\lib\site-packages\rastervision\pipeline\cli.py", line 240, in run_command
    runner=runner)
  File "C:\Users\Administrator\Desktop\rv_0.13\lib\site-packages\rastervision\pipeline\cli.py", line 217, in _run_command
    command_fn()
  File "C:\Users\Administrator\Desktop\rv_0.13\lib\site-packages\rastervision\core\rv_pipeline\rv_pipeline.py", line 134, in train
    backend.train(source_bundle_uri=self.config.source_bundle_uri)
  File "C:\Users\Administrator\Desktop\rv_0.13\lib\site-packages\rastervision\pytorch_backend\pytorch_learner_backend.py", line 75, in train
    learner.main()
  File "C:\Users\Administrator\Desktop\rv_0.13\lib\site-packages\rastervision\pytorch_learner\learner.py", line 180, in main
    self.plot_dataloaders(self.preview_batch_limit)
  File "C:\Users\Administrator\Desktop\rv_0.13\lib\site-packages\rastervision\pytorch_learner\learner.py", line 987, in plot_dataloaders
    batch_limit)
  File "C:\Users\Administrator\Desktop\rv_0.13\lib\site-packages\rastervision\pytorch_learner\learner.py", line 979, in plot_dataloader
    x, y = next(iter(dl))
  File "C:\Users\Administrator\Desktop\rv_0.13\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "C:\Users\Administrator\Desktop\rv_0.13\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Administrator\Desktop\rv_0.13\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'AlbumentationsDataset.__init__.<locals>.<lambda>'

(rv_0.13) C:\Users\Administrator\Downloads>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by AdeelH** [comment]
See #1164
