### ISSUE TITLE
rastervision run local command error

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1217]
i'm running this command.

rastervision run local cowc_potsdam.py -a raw_uri "C:\Users\Administrator\Desktop\AIML\Image" -a processed_uri "C:\Users\Administrator\Desktop\AIML\Image" -a root_uri "C:\Users\Administrator\Desktop\AIML\Image

it will generate makefile and pipeline-config.json file and give this error also.

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\3.6.2\Scripts\rastervision.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\desktop\3.6.2\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\desktop\3.6.2\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\desktop\3.6.2\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\desktop\3.6.2\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\desktop\3.6.2\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\administrator\desktop\3.6.2\lib\site-packages\rastervision\pipeline\cli.py", line 160, in run
    _run_pipeline(cfg, runner, tmp_dir, splits, commands)
  File "c:\users\administrator\desktop\3.6.2\lib\site-packages\rastervision\pipeline\cli.py", line 119, in _run_pipeline
    runner.run(cfg_json_uri, pipeline, commands, num_splits=splits)
  File "c:\users\administrator\desktop\3.6.2\lib\site-packages\rastervision\pipeline\runner\local_runner.py", line 99, in run
    process = Popen(['make', '-j', '-f', makefile_path])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 992, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by AdeelH** [comment]
https://github.com/azavea/raster-vision/issues/1164#issuecomment-858379810
