### ISSUE TITLE
Semantic segmentation integration tests are failing

### ISSUE THREAD

**Issue by colekettler** [azavea/raster-vision#1220]
The two semantic segmentation integration tests [here](https://github.com/azavea/raster-vision/blob/d9d114054095ab837c29925f4db2e2d6ba62013e/integration_tests/integration_tests.py#L48-L61) are failing.

```
------
Test: semantic_segmentation.basic
{'kwargs': {'nochip': True},
Message: raised an exception while running
 'module': 'integration_tests.semantic_segmentation',
Details: Traceback (most recent call last):
 'task': 'semantic_segmentation'}
  File "/opt/src/integration_tests/integration_tests.py", line 269, in run_test
    _run_pipeline(pipeline_cfg, runner, tmp_dir)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 129, in _run_pipeline
    pipeline_run_name=pipeline_run_name)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/runner/inprocess_runner.py", line 25, in run
    _run_command(cfg_json_uri, command, 0, 1)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 217, in _run_command
    command_fn()
  File "/opt/src/rastervision_core/rastervision/core/rv_pipeline/semantic_segmentation.py", line 132, in chip
    return super().chip(*args, **kwargs)
  File "/opt/src/rastervision_core/rastervision/core/rv_pipeline/rv_pipeline.py", line 127, in chip
    chip_scene(s.build(class_cfg, self.tmp_dir), TRAIN)
  File "/opt/src/rastervision_core/rastervision/core/data/scene_config.py", line 58, in build
    if self.label_source is not None else None)
  File "/opt/src/rastervision_core/rastervision/core/data/label_source/semantic_segmentation_label_source_config.py", line 31, in build
    rgb_class_config=self.rgb_class_config)
  File "/opt/src/rastervision_core/rastervision/core/data/label_source/semantic_segmentation_label_source.py", line 53, in __init__
    rgb_class_config)
  File "/opt/src/rastervision_core/rastervision/core/data/label_source/segmentation_class_transformer.py", line 13, in __init__
    null_class_id = class_config.get_null_class_id()
  File "/opt/src/rastervision_core/rastervision/core/data/class_config.py", line 35, in get_null_class_id
    raise ValueError('null_class is not set')
ValueError: null_class is not set
```

```
------
Test: semantic_segmentation.nochip
Message: raised an exception while running
Details: Traceback (most recent call last):
  File "/opt/src/integration_tests/integration_tests.py", line 269, in run_test
    _run_pipeline(pipeline_cfg, runner, tmp_dir)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 129, in _run_pipeline
    pipeline_run_name=pipeline_run_name)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/runner/inprocess_runner.py", line 25, in run
    _run_command(cfg_json_uri, command, 0, 1)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 217, in _run_command
    command_fn()
  File "/opt/src/rastervision_core/rastervision/core/rv_pipeline/rv_pipeline.py", line 134, in train
    backend.train(source_bundle_uri=self.config.source_bundle_uri)
  File "/opt/src/rastervision_pytorch_backend/rastervision/pytorch_backend/pytorch_learner_backend.py", line 74, in train
    learner = self.learner_cfg.build(self.tmp_dir, training=True)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/semantic_segmentation_learner_config.py", line 157, in build
    training=training)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner.py", line 155, in __init__
    self.setup_model(model_def_path=model_def_path)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner.py", line 275, in setup_model
    self.model = self.build_model()
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/semantic_segmentation_learner.py", line 37, in build_model
    model = models.segmentation.segmentation._segm_resnet(
AttributeError: module 'torchvision.models.segmentation.segmentation' has no attribute '_segm_resnet'
```

Full error output can be seen in [this workflow run](https://github.com/azavea/raster-vision/runs/3135969668).

They are being disabled in #1218 temporarily until we can prioritize a fix.

**Comment by AdeelH** [comment]
This error is a result of #1168. `_segm_resnet` has been changed to `_segm_model` in the new torchvision release.

**Comment by colekettler** [comment]
@AdeelH Thank you! I subbed out `_seg_resnet` for `_segm_model` to see if I could get those tests passing in #1129. Unfortunately I'm still running into some `null_class is not set` errors which I'm not equipped to fix right now. I'll leave this issue open for folks who are more familiar with the Raster Vision class implementations.

**Comment by AdeelH** [comment]
Yeah, you don't need to fix it in this PR. Thanks for trying that out.
