### ISSUE TITLE
about semantic_sementation to predict

### ISSUE THREAD

**Issue by LinNiu** [azavea/raster-vision#1251]
## 🐛 Bug

Traceback (most recent call last):
  File "/home/libo/anaconda3/envs/pre/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/libo/anaconda3/envs/pre/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/libo/anaconda3/envs/pre/lib/python3.6/site-packages/rastervision/pipeline/cli.py", line 248, in <module>
    main()
  File "/home/libo/anaconda3/envs/pre/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/libo/anaconda3/envs/pre/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/libo/anaconda3/envs/pre/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/libo/anaconda3/envs/pre/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/libo/anaconda3/envs/pre/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/libo/anaconda3/envs/pre/lib/python3.6/site-packages/rastervision/core/cli.py", line 72, in predict
    channel_order)
  File "/home/libo/anaconda3/envs/pre/lib/python3.6/site-packages/rastervision/core/predictor.py", line 52, in __init__
    self.scene = self.config.dataset.validation_scenes[0]
AttributeError: 'LearnerPipelineConfig' object has no attribute 'dataset'

python -m rastervision.pipeline.cli predict model-bundle.zip MS600_SET_003.TIF res

## Expected behavior

I  want to use model.zip for predicting  one picture (tif) ,but there is one question about "AttributeError: 'LearnerPipelineConfig' object has no attribute 'dataset'" .

## Environment

Running Raster Vision directly in Windows is not supported, and we recommend that you run it from within a Docker container.
ubutun 20
python=3.6
rastervision=0.13.1
gdal=3.0.4

 - How you installed and are running Raster Vision (pip install on local vs. inside Docker image):
 - Raster Vision version or commit:
 - OS (e.g., Linux):ubutun20
 - Python version:3.6
 - CUDA/cuDNN version if running on GPU:11.1/8.0
 - Any other relevant information:

**Comment by AdeelH** [comment]
For the predict command, you are supposed to use the bundle produced by the `bundle` command. That is, instead of using `train/model-bundle.zip`, you should use `bundle/model-bundle.zip`.

**Comment by LinNiu** [comment]
rastervision run local last_work.py \
    -a raw_uri $RAW_URI -a processed_uri $PROCESSED_URI -a root_uri $ROOT_URI \
    -a test True -a external_model False -a multiband True --splits 2
this is my command to train. Why can not find  the dir about bundle?

**Comment by AdeelH** [comment]
What do you see in your $ROOT_URI directory after the job is completed?
