### ISSUE TITLE
ValueError("No Shapely geometry can be created from null value")

### ISSUE THREAD

**Issue by manapshymyr-OB** [azavea/raster-vision#1325]
I am trying to implement the tiny_spacenet.py to the Sentinel-2 images. I have not found how to create the labels (.geojson files), if there is any direction on how to create labels from scratch I would be happy to get it.

Anyway, I have extracted building labels from Open Street Map data. Comparing the structure of the geojson which used in the example (train_label_uri = f'{base_uri}/buildings_AOI_2_Vegas_img205.geojson'), realized that my  geojson does not contain any info in the 'properties' item. Then I manually added properties data to my labels extracted from OSM. However, I am getting the following error:

```
2022-01-26 22:25:35:rastervision.pytorch_learner.learner: INFO - Loading checkpoint from /opt/data/output/train/last-model.pth
TopologyException: unable to assign hole to a shell
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 248, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 240, in run_command
    runner=runner)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 217, in _run_command
    command_fn()
  File "/opt/src/rastervision_core/rastervision/core/rv_pipeline/rv_pipeline.py", line 134, in train
    backend.train(source_bundle_uri=self.config.source_bundle_uri)
  File "/opt/src/rastervision_pytorch_backend/rastervision/pytorch_backend/pytorch_learner_backend.py", line 74, in train
    learner = self.learner_cfg.build(self.tmp_dir, training=True)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/semantic_segmentation_learner_config.py", line 157, in build
    training=training)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner.py", line 166, in __init__
    self.setup_training(loss_def_path=loss_def_path)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner.py", line 221, in setup_training
    self.setup_data()
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner.py", line 580, in setup_data
    train_ds, valid_ds, test_ds = self.get_datasets()
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner.py", line 538, in get_datasets
    return self._get_datasets()
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner.py", line 478, in _get_datasets
    return self._get_geo_datasets()
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner.py", line 531, in _get_geo_datasets
    test_tf=test_tf)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner_config.py", line 546, in make_datasets
    self.scene_to_dataset(s, train_tf, **kwargs) for s in train_scenes
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner_config.py", line 546, in <listcomp>
    self.scene_to_dataset(s, train_tf, **kwargs) for s in train_scenes
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/semantic_segmentation_learner_config.py", line 114, in scene_to_dataset
    transform=transform)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/dataset/semantic_segmentation_dataset.py", line 104, in __init__
    transform_type=TransformType.semantic_segmentation)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/dataset/dataset.py", line 260, in __init__
    to_pytorch=to_pytorch)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/dataset/dataset.py", line 107, in __init__
    with self.scene.activate(stay_activated=True):
  File "/opt/src/rastervision_core/rastervision/core/data/activate_mixin.py", line 46, in __enter__
    manager.__enter__()
  File "/opt/src/rastervision_core/rastervision/core/data/activate_mixin.py", line 46, in __enter__
    manager.__enter__()
  File "/opt/src/rastervision_core/rastervision/core/data/activate_mixin.py", line 46, in __enter__
    manager.__enter__()
  [Previous line repeated 1 more time]
  File "/opt/src/rastervision_core/rastervision/core/data/activate_mixin.py", line 27, in __enter__
    self.activate()
  File "/opt/src/rastervision_core/rastervision/core/data/activate_mixin.py", line 63, in do_activate
    self._activate()
  File "/opt/src/rastervision_core/rastervision/core/data/raster_source/rasterized_source.py", line 112, in _activate
    geojson = self.vector_source.get_geojson()
  File "/opt/src/rastervision_core/rastervision/core/data/vector_source/vector_source.py", line 150, in get_geojson
    to_map_coords=to_map_coords)
  File "/opt/src/rastervision_core/rastervision/core/data/vector_source/vector_source.py", line 84, in transform_geojson
    poly_buf = g.buffer(0)
  File "/opt/conda/lib/python3.6/site-packages/shapely/geometry/base.py", line 584, in buffer
    return geom_factory(self.impl['buffer'](self, distance, res))
  File "/opt/conda/lib/python3.6/site-packages/shapely/geometry/base.py", line 76, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value
/opt/data/output/Makefile:6: recipe for target '0' failed
make: *** [0] Error 1

```

Can you please give some hints to solve this problem? 
geojsons are available here: https://drive.google.com/drive/folders/19TH_wHiVg51PHXeqxb3p1bm5X1FhycEL?usp=sharing

**Comment by manapshymyr-OB** [comment]
@AdeelH

**Comment by lewfish** [comment]
@manapshymyr-OB: I heard from Adeel that this doesn't occur when you used a subset of the GeoJSON file. Could you point us to that file? That will help us troubleshoot. But, since you have things working, I will consider this issue lower priority.,
