### ISSUE TITLE
`predict` does not work with some Model Zoo examples.

### ISSUE THREAD

**Issue by theoway** [azavea/raster-vision#1385]
## 🐛 Bug

When running `predict` on model SpaceNet Vegas Roads & COWC Potsdam (Cars), it reports error. Here's the command that has been used:
`python -m rastervision.pipeline.cli predict /opt/src/code/spacenet-roads.zip /opt/src/code/car_parking.tif /opt/src/code/results/ --channel-order "0 1 2"`

I tired both ways, with and without channel order, same error is thrown:
```Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 250, in <module>
    _main()
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 246, in _main
    main()
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/src/rastervision_core/rastervision/core/cli.py", line 66, in predict
    predictor.predict([image_uri], label_uri)
  File "/opt/src/rastervision_core/rastervision/core/predictor.py", line 126, in predict
    self.pipeline.predict()
  File "/opt/src/rastervision_core/rastervision/core/rv_pipeline/rv_pipeline.py", line 172, in predict
    self.backend.load_model()
  File "/opt/src/rastervision_pytorch_backend/rastervision/pytorch_backend/pytorch_learner_backend.py", line 120, in load_model
    self.learner = self._build_learner_from_bundle(training=False)
  File "/opt/src/rastervision_pytorch_backend/rastervision/pytorch_backend/pytorch_learner_backend.py", line 129, in _build_learner_from_bundle
    bundle_uri, self.tmp_dir, cfg=cfg, training=training)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner.py", line 1108, in from_model_bundle
    training=training)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/semantic_segmentation_learner_config.py", line 149, in build
    training=training)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner.py", line 159, in __init__
    self.setup_model(model_def_path=model_def_path)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner.py", line 276, in setup_model
    self.model = self.build_model()
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/semantic_segmentation_learner.py", line 58, in build_model
    pretrained=pretrained)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/utils/utils.py", line 205, in adjust_conv_channels
    if in_channels > old_conv.in_channels:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

## To Reproduce

1.  Run the `predict` command on either **SpaceNet Vegas Roads or COWC Potsdam (Cars)** bundle.

## Expected behavior

It should perform the prediction and store the results as expected.

## Environment

Docker image built on `master` branch, commit: `b58985231a7383417459e9fadb3190b480167223`
## Additional context

So far, only **ISPRS Potsdam** works perfectly well with latest `master` version rastervision image.

**Comment by theoway** [comment]
I'd be more than happy to fix this, if someone can give me some initial pointers.

**Comment by Vijay-P1999** [comment]
@theoway @AdeelH I faced the same error

> TypeError: '>' not supported between instances of 'NoneType' and 'int'

I tried changing the channel order, but no changes.

**Comment by AdeelH** [comment]
Thanks for the report! This should be fixed now.
