### ISSUE TITLE
ERROR 4: Unable to open EPSG support file gcs.csv

### ISSUE THREAD

**Issue by gaussiangit** [azavea/raster-vision#1419]
```
2022-06-15 05:33:14:rastervision.pytorch_learner.learner: INFO - Using device: cuda
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
Traceback (most recent call last):
  File "rasterio/_base.pyx", line 1310, in rasterio._base._osr_from_crs
  File "rasterio/_err.pyx", line 176, in rasterio._err.exc_wrap_int
rasterio._err.CPLE_OpenFailedError: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
```

**Comment by AdeelH** [comment]
You need to set that environment variable as shown in the `Dockerfile`: https://github.com/azavea/raster-vision/blob/eb67d12e1c88f04387873444c7c9b05f767280e6/Dockerfile#L28-L29

The exact path might be different depending on your environment.
