### ISSUE TITLE
Batch submit jobs InvalidSignatureException

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#169]
Sometimes when submitting a Batch job in the VM, I get the following InvalidSignatureException error. The workaround is to reload the VM and try again.
```
root@59542c61e46b:/opt/src# ./scripts/batch_submit.py lf/pytorch     "python -m rv.classification.run train \
        s3://raster-vision-od/configs/training/cl/merced.json \
        s3://raster-vision-od/training-data/cl/merced-train.zip \
        s3://raster-vision-od/training-data/cl/merced-test.zip \
        s3://raster-vision-od/trained-models/cl/merced"     --attempts 1
Traceback (most recent call last):
  File "./scripts/batch_submit.py", line 52, in <module>
    batch_submit()
  File "/opt/conda/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./scripts/batch_submit.py", line 44, in batch_submit
    'attempts': attempts
  File "/opt/conda/lib/python3.5/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/conda/lib/python3.5/site-packages/botocore/client.py", line 605, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the SubmitJob operation: Signature expired: 20171214T213244Z is now earlier than 20171214T213657Z (20171214T214157Z - 5 min.)
```

**Comment by hectcastro** [comment]
This may be occurring if your VM clock is getting out of sync. Do you have a sense for if this occurs after you wake your workstation up from sleep?

**Comment by lewfish** [comment]
I'm not sure if it happens then. I just tried submitting a job after waking it up, and it worked fine.

**Comment by lewfish** [comment]
This problem should go away once we stop using Vagrant in https://github.com/azavea/raster-vision/issues/222
