### ISSUE TITLE
`RasterioSource.get_chip()` raises `TypeError: slice indices must be integers or None or have an __index__ method`

### ISSUE THREAD

**Issue by lcoandrade** [azavea/raster-vision#2257]
## 🐛 Bug

When running:
```
learner = SemanticSegmentationLearner(
    cfg=learner_cfg,
    output_dir=OUTPUT_DIR,
    train_ds=train_set,
    valid_ds=valid_set,
    test_ds=test_set,
    training=True,
)

learner.log_data_stats()

learner.train(epochs=EPOCHS)
```

I get:
```
2024-10-09 19:27:05:rastervision.pytorch_learner.learner: INFO - train_ds: 10800 items
2024-10-09 19:27:05:rastervision.pytorch_learner.learner: INFO - valid_ds: 3600 items
2024-10-09 19:27:05:rastervision.pytorch_learner.learner: INFO - test_ds: 3600 items
2024-10-09 19:27:05:rastervision.pytorch_learner.learner: INFO - Plotting sample training batch.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[45], line 3
      1 start = timeit.default_timer() # Measuring the time
----> 3 learner.train(epochs=EPOCHS)
      5 print("The time taken to train was: ", timeit.default_timer() - start)

File /opt/conda/lib/python3.10/site-packages/rastervision/pytorch_learner/learner.py:448, in Learner.train(self, epochs)
    441     mp.start_processes(
    442         self._run_train_distributed,
    443         args=(self.ddp_world_size, start_epoch, end_epoch),
    444         nprocs=self.ddp_world_size,
    445         join=True,
    446         start_method=self.ddp_start_method)
    447 else:
--> 448     self._train(start_epoch, end_epoch)

File /opt/conda/lib/python3.10/site-packages/rastervision/pytorch_learner/learner.py:452, in Learner._train(self, start_epoch, end_epoch)
    450 def _train(self, start_epoch: int, end_epoch: int):  # pragma: no cover
    451     """Training loop."""
--> 452     self.on_train_start()
    453     for epoch in range(start_epoch, end_epoch):
    454         log.info(f'epoch: {epoch}')

File /opt/conda/lib/python3.10/site-packages/rastervision/pytorch_learner/learner.py:562, in Learner.on_train_start(self)
    560 """Hook that is called at start of train routine."""
    561 self.log_data_stats()
--> 562 self.plot_dataloaders(self.cfg.data.preview_batch_limit)

File /opt/conda/lib/python3.10/site-packages/rastervision/pytorch_learner/learner.py:1368, in Learner.plot_dataloaders(self, batch_limit, show)
   1366 if self.train_dl:
   1367     log.info('Plotting sample training batch.')
-> 1368     self.plot_dataloader(
   1369         self.train_dl,
   1370         output_path=join(self.output_dir_local,
   1371                          'dataloaders/train.png'),
   1372         batch_limit=batch_limit,
   1373         show=show)
   1374 if self.valid_dl:
   1375     log.info('Plotting sample validation batch.')

File /opt/conda/lib/python3.10/site-packages/rastervision/pytorch_learner/learner.py:1358, in Learner.plot_dataloader(self, dl, output_path, batch_limit, show)
   1352 def plot_dataloader(self,
   1353                     dl: DataLoader,
   1354                     output_path: str,
   1355                     batch_limit: int | None = None,
   1356                     show: bool = False):
   1357     """Plot images and ground truth labels for a DataLoader."""
-> 1358     x, y = next(iter(dl))
   1359     self.visualizer.plot_batch(
   1360         x, y, output_path, batch_limit=batch_limit, show=show)

File /opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:630, in _BaseDataLoaderIter.__next__(self)
    627 if self._sampler_iter is None:
    628     # TODO(https://github.com/pytorch/pytorch/issues/76750)
    629     self._reset()  # type: ignore[call-arg]
--> 630 data = self._next_data()
    631 self._num_yielded += 1
    632 if self._dataset_kind == _DatasetKind.Iterable and \
    633         self._IterableDataset_len_called is not None and \
    634         self._num_yielded > self._IterableDataset_len_called:

File /opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:1344, in _MultiProcessingDataLoaderIter._next_data(self)
   1342 else:
   1343     del self._task_info[idx]
-> 1344     return self._process_data(data)

File /opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:1370, in _MultiProcessingDataLoaderIter._process_data(self, data)
   1368 self._try_put_index()
   1369 if isinstance(data, ExceptionWrapper):
-> 1370     data.reraise()
   1371 return data

File /opt/conda/lib/python3.10/site-packages/torch/_utils.py:706, in ExceptionWrapper.reraise(self)
    702 except TypeError:
    703     # If the exception takes multiple arguments, don't try to
    704     # instantiate since we don't know how to
    705     raise RuntimeError(msg) from None
--> 706 raise exception

TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 50, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 420, in __getitems__
    return [self.dataset[self.indices[idx]] for idx in indices]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 420, in <listcomp>
    return [self.dataset[self.indices[idx]] for idx in indices]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 350, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/opt/conda/lib/python3.10/site-packages/rastervision/pytorch_learner/dataset/dataset.py", line 491, in __getitem__
    out = super().__getitem__(window)
  File "/opt/conda/lib/python3.10/site-packages/rastervision/pytorch_learner/dataset/dataset.py", line 68, in __getitem__
    val = self.orig_dataset[key]
  File "/opt/conda/lib/python3.10/site-packages/rastervision/core/data/scene.py", line 74, in __getitem__
    y = self.label_source[key]
  File "/opt/conda/lib/python3.10/site-packages/rastervision/core/data/label_source/semantic_segmentation_label_source.py", line 101, in __getitem__
    return self.get_label_arr(key)
  File "/opt/conda/lib/python3.10/site-packages/rastervision/core/data/label_source/semantic_segmentation_label_source.py", line 79, in get_label_arr
    label_arr = self.raster_source.get_chip(window)
  File "/opt/conda/lib/python3.10/site-packages/rastervision/core/data/raster_source/rasterio_source.py", line 172, in get_chip
    chip = self._get_chip(window, out_shape=out_shape, bands=bands)
  File "/opt/conda/lib/python3.10/site-packages/rastervision/core/data/raster_source/rasterio_source.py", line 147, in _get_chip
    chip = fill_overflow(self.bbox, window, chip)
  File "/opt/conda/lib/python3.10/site-packages/rastervision/core/data/utils/raster.py", line 32, in fill_overflow
    chip[..., ymax:, :, :] = fill_value
TypeError: slice indices must be integers or None or have an __index__ method
```

## To Reproduce

Just run the code above in my Kaggle notebook (https://www.kaggle.com/code/luizclaudioandrade/curso-geo1)

## Expected behavior

Train the model.

## Environment

kaggle.com

## Additional info
When I run the same thing in https://www.kaggle.com/code/luizclaudioandrade/building-footprint-rastervision, it works.

**Comment by AdeelH** [comment]
Thanks for the report. This seems to be a weird non-deterministic pyproj bug. Looking into it.

**Comment by lcoandrade** [comment]
I was facing some weird behavior when trying to use the segmentation visualizer as well. It seemed random.

**Comment by AdeelH** [comment]
Until this fix is released on PyPi, you can try installing RV from GitHub like so:

```
!git clone --depth=1 https://github.com/azavea/raster-vision.git

%pip install raster-vision/rastervision_pipeline;
%pip install raster-vision/rastervision_aws_s3;
%pip install raster-vision/rastervision_core;
%pip install raster-vision/rastervision_pytorch_learner;
```

**Comment by lcoandrade** [comment]
Thank you!!!!
