### ISSUE TITLE
Bad file descriptor during export

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#285]
There is an intermittent bug that happens about 10% of the time when training a model locally. (It might also happen remotely, but I've never seen it happen.) It happens when calling the `export_inference_graph` command that is part of TF OD API and results in a 'Bad file descriptor' error. I only saw it after we switched versions of TF OD API (or was it when upgrading TF?). 

```
INFO:tensorflow:Recording summary at step 0.
INFO:tensorflow:Recording summary at step 0.

INFO:tensorflow:global step 1: loss = 26.4984 (8.012 sec/step)
INFO:tensorflow:global step 1: loss = 26.4984 (8.012 sec/step)
INFO:tensorflow:global step 2: loss = 16.3846 (1.330 sec/step)
INFO:tensorflow:global step 2: loss = 16.3846 (1.330 sec/step)
INFO:tensorflow:global step 3: loss = 15.7465 (1.356 sec/step)
INFO:tensorflow:global step 3: loss = 15.7465 (1.356 sec/step)
INFO:tensorflow:global step 4: loss = 16.6867 (1.453 sec/step)
INFO:tensorflow:global step 4: loss = 16.6867 (1.453 sec/step)
INFO:tensorflow:Stopping Training.
INFO:tensorflow:Stopping Training.
INFO:tensorflow:Finished training! Saving model to disk.
INFO:tensorflow:Finished training! Saving model to disk.
Exporting checkpoint /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/train/model.ckpt-4...
['python', '/opt/tf-models/object_detection/export_inference_graph.py', '--input_type', 'image_tensor', '--pipeline_config_path', '/opt/data/tmp/tmpzn28ruj2/tmpatcxw33l/ml.config', '--trained_checkpoint_prefix', '/opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/train/model.ckpt-4', '--output_directory', '/opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output']
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From /opt/tf-models/object_detection/exporter.py:358: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
2018-06-13 20:31:58.789365: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-06-13 20:31:59.418078: W tensorflow/core/framework/op_kernel.cc:1198] Failed precondition: /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/train/model.ckpt-4.index; Bad file descriptor
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/train/model.ckpt-4.index; Bad file descriptor
	 [[Node: save/RestoreV2_106 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_106/tensor_names, save/RestoreV2_106/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/tf-models/object_detection/export_inference_graph.py", line 147, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/opt/tf-models/object_detection/export_inference_graph.py", line 143, in main
    FLAGS.output_directory, input_shape)
  File "/opt/tf-models/object_detection/exporter.py", line 460, in export_inference_graph
    graph_hook_fn=None)
  File "/opt/tf-models/object_detection/exporter.py", line 410, in _export_inference_graph
    trained_checkpoint_prefix=checkpoint_to_use)
  File "/opt/tf-models/object_detection/exporter.py", line 323, in write_graph_and_checkpoint
    saver.restore(sess, trained_checkpoint_prefix)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1686, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/train/model.ckpt-4.index; Bad file descriptor
	 [[Node: save/RestoreV2_106 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_106/tensor_names, save/RestoreV2_106/shape_and_slices)]]

Caused by op 'save/RestoreV2_106', defined at:
  File "/opt/tf-models/object_detection/export_inference_graph.py", line 147, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/opt/tf-models/object_detection/export_inference_graph.py", line 143, in main
    FLAGS.output_directory, input_shape)
  File "/opt/tf-models/object_detection/exporter.py", line 460, in export_inference_graph
    graph_hook_fn=None)
  File "/opt/tf-models/object_detection/exporter.py", line 410, in _export_inference_graph
    trained_checkpoint_prefix=checkpoint_to_use)
  File "/opt/tf-models/object_detection/exporter.py", line 319, in write_graph_and_checkpoint
    tf.import_graph_def(inference_graph_def, name='')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 316, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 554, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/train/model.ckpt-4.index; Bad file descriptor
	 [[Node: save/RestoreV2_106 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_106/tensor_names, save/RestoreV2_106/shape_and_slices)]]

Traceback (most recent call last):
  File "/usr/lib/python3.5/shutil.py", line 538, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/frozen_inference_graph.pb' -> '/opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/rastervision/utils/chain_workflow.py", line 455, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/src/rastervision/utils/chain_workflow.py", line 451, in main
    _main(workflow_uri, tasks, remote, simulated_remote, branch, run)
  File "/opt/src/rastervision/utils/chain_workflow.py", line 440, in _main
    workflow.local_run(tasks)
  File "/opt/src/rastervision/utils/chain_workflow.py", line 415, in local_run
    run._train(self.path_generator.train_config_uri)
  File "/opt/src/rastervision/run.py", line 32, in _train
    command.run()
  File "/opt/src/rastervision/commands/train.py", line 10, in run
    self.ml_task.train(self.options)
  File "/opt/src/rastervision/core/ml_task.py", line 143, in train
    self.backend.train(self.class_map, options)
  File "/opt/src/rastervision/ml_backends/tf_object_detection_api.py", line 469, in train
    export_py=export_py)
  File "/opt/src/rastervision/ml_backends/tf_object_detection_api.py", line 233, in export_inference_graph
    shutil.move(inference_graph_path, output_path)
  File "/usr/lib/python3.5/shutil.py", line 552, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.5/shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/frozen_inference_graph.pb'
Terminating 15201...
root@e83362e84185:/opt/src#
root@e83362e84185:/opt/src#
```

**Comment by lewfish** [comment]
After this crashed, I ran the export command directly and it crashed about 10% of the time again.

```
root@e83362e84185:/opt/src# python /opt/tf-models/object_detection/export_inference_graph.py     --input_type image_tensor --pipeline_config_path /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/backend.config     --trained_checkpoint_prefix /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/train/model.ckpt-4     --output_directory /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From /opt/tf-models/object_detection/exporter.py:358: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
2018-06-13 20:52:54.635777: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-06-13 20:52:58.221842: W tensorflow/core/framework/op_kernel.cc:1198] Failed precondition: /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/train/model.ckpt-4.index; Bad file descriptor
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/train/model.ckpt-4.index; Bad file descriptor
	 [[Node: save/RestoreV2_89 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_89/tensor_names, save/RestoreV2_89/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/tf-models/object_detection/export_inference_graph.py", line 147, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/opt/tf-models/object_detection/export_inference_graph.py", line 143, in main
    FLAGS.output_directory, input_shape)
  File "/opt/tf-models/object_detection/exporter.py", line 460, in export_inference_graph
    graph_hook_fn=None)
  File "/opt/tf-models/object_detection/exporter.py", line 425, in _export_inference_graph
    initializer_nodes='')
  File "/opt/tf-models/object_detection/exporter.py", line 72, in freeze_graph_with_def_protos
    saver.restore(sess, input_checkpoint)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1686, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/train/model.ckpt-4.index; Bad file descriptor
	 [[Node: save/RestoreV2_89 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_89/tensor_names, save/RestoreV2_89/shape_and_slices)]]

Caused by op 'save/RestoreV2_89', defined at:
  File "/opt/tf-models/object_detection/export_inference_graph.py", line 147, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/opt/tf-models/object_detection/export_inference_graph.py", line 143, in main
    FLAGS.output_directory, input_shape)
  File "/opt/tf-models/object_detection/exporter.py", line 460, in export_inference_graph
    graph_hook_fn=None)
  File "/opt/tf-models/object_detection/exporter.py", line 425, in _export_inference_graph
    initializer_nodes='')
  File "/opt/tf-models/object_detection/exporter.py", line 67, in freeze_graph_with_def_protos
    tf.import_graph_def(input_graph_def, name='')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 316, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 554, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/train/model.ckpt-4.index; Bad file descriptor
	 [[Node: save/RestoreV2_89 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_89/tensor_names, save/RestoreV2_89/shape_and_slices)]]
```

**Comment by lewfish** [comment]
The file it is complaining about `/opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/train/model.ckpt-4.index`exists and is readable according to `ls -al`

**Comment by lewfish** [comment]
The only TF bad descriptor thing I could find has no replay: https://stackoverflow.com/questions/48371559/tensorflow-python-framework-errors-impl-failedpreconditionerror-bad-file-descrip

In general, this seems to happen when there is a mismatch between the open/closed status of a file Python object and the actual status on the file system.
https://stackoverflow.com/questions/7686275/what-can-lead-to-ioerror-errno-9-bad-file-descriptor-during-os-system/

**Comment by lewfish** [comment]
I'm using this script to test:

```
#!/bin/bash

set -e

COUNT=1
while true; do
    rm -rf /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/saved_model/

    echo "Run number $COUNT"
    let "COUNT++"
    python /opt/tf-models/object_detection/export_inference_graph.py \
        --input_type image_tensor --pipeline_config_path /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/backend.config \
        --trained_checkpoint_prefix /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/train/model.ckpt-4 \
        --output_directory /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output
done
```

**Comment by lewfish** [comment]
I found that using TF 1.8 seems to fix this problem, although I'm not totally sure since it's intermittent. I'm still seeing if there are any negative consequences of using that version.
