### ISSUE TITLE
make_training_chips is failing

### ISSUE THREAD

**Issue by mikemommsen** [azavea/raster-vision#372]
this is my stack dump

root@4e99d917b522:/opt/src# python -m rastervision.workflows.chain               /opt/data/machine-learning-training-data-test/workflow-configs/object-detection/config.json               compute_raster_stats make_training_chips train              --run
Root temporary directory cannot be used: None. Using root: /opt/data/tmp/
Temporary directory is: /opt/data/tmp/tmpnfnhcojk
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Generating and saving config files...
Loading GeoTiffFFiles...
Downloading and building VRT...
0...10...20...30...40...50...60...70...80...90...100 - done.
Loading GeoTiffFFiles...
Downloading and building VRT...
0...10...20...30...40...50...60...70...80...90...100 - done.
/usr/local/lib/python3.5/dist-packages/npstreams/stats.py:174: RuntimeWarning: invalid value encountered in double_scalars
  yield from map(lambda element: truediv(*element), primitive)
/usr/local/lib/python3.5/dist-packages/npstreams/stats.py:122: RuntimeWarning: invalid value encountered in double_scalars
  yield from map(lambda element: truediv(*element), primitive)
/usr/local/lib/python3.5/dist-packages/npstreams/stats.py:293: RuntimeWarning: invalid value encountered in long_scalars
  yield (sq_avg - avg**2) * (swgt / (swgt - ddof))
Loading GeoTiffFFiles...
Downloading and building VRT...
0...10...20...30...40...50...60...70...80...90...100 - done.
Loading GeoTiffFFiles...
Downloading and building VRT...
0...10...20...30...40...50...60...70...80...90...100 - done.
Making train chips for scene: 2-10Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/rastervision/workflows/chain.py", line 489, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/src/rastervision/workflows/chain.py", line 485, in main
    run=run)
  File "/opt/src/rastervision/workflows/chain.py", line 468, in _main
    workflow.local_run(tasks)
  File "/opt/src/rastervision/workflows/chain.py", line 436, in local_run
    self.path_generator.make_training_chips_config_uri)
  File "/opt/src/rastervision/run.py", line 22, in _make_training_chips
    command.run()
  File "/opt/src/rastervision/commands/make_training_chips.py", line 13, in run
    self.validation_scenes, self.options)
  File "/opt/src/rastervision/core/ml_task.py", line 140, in make_training_chips
    processed_training_results = _process_scenes(train_scenes, TRAIN)
  File "/opt/src/rastervision/core/ml_task.py", line 137, in _process_scenes
    return [_process_scene(scene, type_) for scene in scenes]
  File "/opt/src/rastervision/core/ml_task.py", line 137, in <listcomp>
    return [_process_scene(scene, type_) for scene in scenes]
  File "/opt/src/rastervision/core/ml_task.py", line 121, in _process_scene
    windows = self.get_train_windows(scene, options)
  File "/opt/src/rastervision/ml_tasks/object_detection.py", line 110, in get_train_windows
    options)
  File "/opt/src/rastervision/ml_tasks/object_detection.py", line 73, in make_pos_windows
    return _make_chip_pos_windows(image_extent, label_store, options)
  File "/opt/src/rastervision/ml_tasks/object_detection.py", line 41, in _make_chip_pos_windows
    window = box.make_random_square_container(chip_size)
  File "/opt/src/rastervision/core/box.py", line 101, in make_random_square_container
    rand_y = random.randint(lb, ub)
  File "/usr/lib/python3.5/random.py", line 218, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.5/random.py", line 196, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (2710,2515, -195)
root@4e99d917b522:/opt/src# exit
exit

**Comment by lewfish** [comment]
I'm not 100% sure without having some test data, but I *think* I know what's causing this. The error message is saying that the lower bound is greater than the upper bound at https://github.com/azavea/raster-vision/blob/develop/src/rastervision/core/box.py#L101. This can only occur if the chip size is smaller than the box for an object. So you must have a big object that doesn't fit inside a chip. We need to guard against this condition and raise an exception if it occurs. We also need to handle this exception by skipping creating a chip for that object. We should also emit a warning that this is happening, and suggest that the chip size be increased.

**Comment by mikemommsen** [comment]
ahhh makes sense. in our data we had some cases where the object was larger than the chip for sure.
