### ISSUE TITLE
Running potsdam semantic segmentation example

### ISSUE THREAD

**Issue by SFrav** [azavea/raster-vision#524]
Great to see Raster vision out there. Excellent work!

I'm trying to get one of your examples up and running (on Ubuntu 18.04). I've tried both locally on my system and through docker and have two different errors.
Running the example on my own system, it made the train chips for the scene and then resulted in the following error: `ModuleNotFoundError: No module named 'object_detection`

the error is less clear in docker. It is something along the lines of:
`Files do not exist and are not supplied by commands: Http://download.tensorflow ...`

I have TF 1.10.1 on both instances.
Adding this to my .bashrc didn't solve the local system issue. 
    export PYTHONPATH=$PYTHONPATH: `pwd` : `pwd` `/slim

Any advice?

P.S. there is a typo in this example. `rastervision run local -e potsdam.semantic_segmentation` should read `rastervision run local -e semantic_segmentation`

**Comment by SFrav** [comment]
This is the command that was run:
`rastervision run local -e semantic_segmentation     -a test_run True -a root_uri /opt/src/output -a data_uri opt/src/data`


The full output from the docker version is below. 
I tested the quick start example (tiny_spacenet) again and it also gives an error. I had that working previously, so I'm sure that I'm just missing something simple.

Output
`Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/rastervision/__main__.py", line 17, in <module>
    rv.main()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/src/rastervision/cli/main.py", line 159, in run
    dry_run=dry_run)
  File "/opt/src/rastervision/runner/experiment_runner.py", line 142, in run
    unique_commands, rerun_commands, skip_file_check=skip_file_check)
  File "/opt/src/rastervision/runner/command_dag.py", line 56, in __init__
    '\t{}\n'.format(',\b\t'.join(missing_files)))
rastervision.core.config.ConfigError: Files do not exist and are not supplied by commands:
    http://download.tensorflow.org/models/deeplabv3_mnv2_pascal_train_aug_2018_01_29.tar.gz
`

**Comment by SFrav** [comment]
The stack trace from running on my system is now more promising. It gets to the point of training the model and then provides the error below

For others wanting to run locally, this is a [nice guide on installing the TF object detection API](https://github.com/wagonhelm/TF_ObjectDetection_API/blob/master/README.md).

I also needed to make a link to the deeplab folder `FT_ObjectDetection_API/models/research/deeplap`
to `/opt/tf-models/deeplab/`

```
Traceback (most recent call last):
  File "/opt/tf-models/deeplab/train.py", line 21, in <module>
    import tensorflow as tf
  File "/home/geostat/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/geostat/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/geostat/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/geostat/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/geostat/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/geostat/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
2018-10-26 19:49:15:rastervision.backend.tf_deeplab: INFO - Exporting frozen graph (/home/geostat/RastervisionWDir/Results/train/potsdam-seg/model)
Traceback (most recent call last):
  File "/home/geostat/.local/bin/rastervision", line 11, in <module>
    sys.exit(main())
  File "/home/geostat/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/geostat/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/geostat/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geostat/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geostat/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/geostat/.local/lib/python3.6/site-packages/rastervision/cli/main.py", line 159, in run
    dry_run=dry_run)
  File "/home/geostat/.local/lib/python3.6/site-packages/rastervision/runner/experiment_runner.py", line 187, in run
    self._run_experiment(command_dag)
  File "/home/geostat/.local/lib/python3.6/site-packages/rastervision/runner/local_experiment_runner.py", line 35, in _run_experiment
    run_commands(tmp_dir)
  File "/home/geostat/.local/lib/python3.6/site-packages/rastervision/runner/local_experiment_runner.py", line 29, in run_commands
    command.run(tmp_dir)
  File "/home/geostat/.local/lib/python3.6/site-packages/rastervision/command/train_command.py", line 16, in run
    self.task.train(tmp_dir)
  File "/home/geostat/.local/lib/python3.6/site-packages/rastervision/task/task.py", line 136, in train
    self.backend.train(tmp_dir)
  File "/home/geostat/.local/lib/python3.6/site-packages/rastervision/backend/tf_deeplab.py", line 607, in train
    num_classes, tfdl_config)
  File "/home/geostat/.local/lib/python3.6/site-packages/rastervision/backend/tf_deeplab.py", line 381, in get_export_args
    get_latest_checkpoint(train_logdir_local)))
  File "/home/geostat/.local/lib/python3.6/site-packages/rastervision/backend/tf_deeplab.py", line 262, in get_latest_checkpoint
    latest = sorted(zip(times, ckpts))[-1][1]
IndexError: list index out of range
````

**Comment by SFrav** [comment]
Ok. This was resolved by running the docker container outside my office firewall.

The link for TF object detection could be included in the install notes, along with details on working linux distributions, cuda installation ect.

I’ll see if I can draft something when I get it all working outside of docker.
