### ISSUE TITLE
Fix CI problem

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#558]
Builds are failing because it looks like `moto` got updated with a breaking change:
```
=====================================================================
ERROR: utils.test_files (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: utils.test_files
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/usr/local/lib/python3.5/dist-packages/pluginbase.py", line 439, in plugin_import
    fromlist, level)
  File "/home/travis/build/azavea/raster-vision/tests/utils/test_files.py", line 7, in <module>
    from moto import mock_s3
  File "/usr/local/lib/python3.5/dist-packages/pluginbase.py", line 439, in plugin_import
    fromlist, level)
  File "/usr/local/lib/python3.5/dist-packages/moto/__init__.py", line 8, in <module>
    from .acm import mock_acm  # flake8: noqa
  File "/usr/local/lib/python3.5/dist-packages/pluginbase.py", line 439, in plugin_import
    fromlist, level)
  File "/usr/local/lib/python3.5/dist-packages/moto/acm/__init__.py", line 2, in <module>
    from .models import acm_backends
  File "/usr/local/lib/python3.5/dist-packages/pluginbase.py", line 439, in plugin_import
    fromlist, level)
  File "/usr/local/lib/python3.5/dist-packages/moto/acm/models.py", line 6, in <module>
    from moto.core import BaseBackend, BaseModel
  File "/usr/local/lib/python3.5/dist-packages/pluginbase.py", line 439, in plugin_import
    fromlist, level)
  File "/usr/local/lib/python3.5/dist-packages/moto/core/__init__.py", line 2, in <module>
    from .models import BaseModel, BaseBackend, moto_api_backend  # flake8: noqa
  File "/usr/local/lib/python3.5/dist-packages/pluginbase.py", line 439, in plugin_import
    fromlist, level)
  File "/usr/local/lib/python3.5/dist-packages/moto/core/models.py", line 12, in <module>
    from botocore.awsrequest import AWSResponse
```

**Comment by lewfish** [comment]
James fixed this.
