### ISSUE TITLE
Handle case where rasterio dataset crs is None

### ISSUE THREAD

**Issue by lossyrob** [azavea/raster-vision#570]
https://github.com/azavea/raster-vision/blob/35ac8b37a511c5b9d6afb6573ee60d7eae2d3957/rastervision/data/crs_transformer/rasterio_crs_transformer.py#L60

```
/usr/local/lib/python3.5/dist-packages/pluginbase.py:439: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  fromlist, level)
2018-11-18 21:53:15:rastervision.data.raster_source.geotiff_source: INFO - Loading GeoTiff files...
/usr/local/lib/python3.5/dist-packages/rasterio/__init__.py:217: NotGeoreferencedWarning: Dataset has no geotransform set. The identity matrix may be returned.
  s = DatasetReader(path, driver=driver, **kwargs)
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/rastervision/__main__.py", line 17, in <module>
    rv.main()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/src/rastervision/cli/main.py", line 240, in predict
    predictor.predict(image_uri, output_uri, export_config)
  File "/opt/src/rastervision/predictor.py", line 130, in predict
    scene = scene_config.create_scene(self.task_config, self.tmp_dir)
  File "/opt/src/rastervision/data/scene_config.py", line 39, in create_scene
    crs_transformer = raster_source.get_crs_transformer()
  File "/opt/src/rastervision/data/raster_source/geotiff_source.py", line 44, in get_crs_transformer
    return RasterioCRSTransformer(self.image_dataset)
  File "/opt/src/rastervision/data/crs_transformer/rasterio_crs_transformer.py", line 18, in __init__
    image_crs = image_dataset.crs['init']
TypeError: 'NoneType' object is not subscriptable
```

We should handle this more gracefully.

**Comment by lossyrob** [comment]
This was fixed as part of https://github.com/azavea/raster-vision/commit/35ac8b37a511c5b9d6afb6573ee60d7eae2d3957
