### ISSUE TITLE
problem when using bath size greater than 2 even if I have 32G RAN and 2 GPU GTX 1050

### ISSUE THREAD

**Issue by asoxien** [azavea/raster-vision#687]

**Comment by asoxien** [comment]
Hello I purchased HP-Z8-G4-Workstation machine with 2 GPU (GTX 1050) and 32G of RAM. Even that I can't execute an tensorflow object detection experiment .with_batch_size(4). Only accepted batch size is 2 and just one GPU used in this configuration even if tensorflow detect two GPUs. For more informations to debug see the following logs: 
2019-02-15 21:01:58:rastervision.backend.tf_object_detection: INFO - 2019-02-15 21:01:58.726988: W tensorflow/core/common_runtime/bfc_allocator.cc:279] ******************x*****************___****_______*******************************************_______

2019-02-15 21:01:58:rastervision.backend.tf_object_detection: INFO - 2019-02-15 21:01:58.727043: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at transpose_op.cc:199 : Resource exhausted: OOM when allocating tensor with shape[32,128,128,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

2019-02-15 21:01:58:rastervision.backend.tf_object_detection: INFO - 2019-02-15 21:01:58.876788: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.12GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.

2019-02-15 21:01:58:rastervision.backend.tf_object_detection: INFO - 2019-02-15 21:01:58.877268: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.02GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.

2019-02-15 21:01:58:rastervision.backend.tf_object_detection: INFO - 2019-02-15 21:01:58.925242: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 576.56MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.

2019-02-15 21:02:08:rastervision.backend.tf_object_detection: INFO - 2019-02-15 21:02:08.925601: W tensorflow/core/common_runtime/bfc_allocator.cc:275] Allocator (GPU_0_bfc) ran out of memory trying to allocate 512.00MiB.  Current allocation summary follows.

2019-02-15 21:02:09:rastervision.backend.tf_object_detection: INFO - 2019-02-15 21:02:09.494320: W tensorflow/core/common_runtime/bfc_allocator.cc:279] ******************x****************************___**********************************************____

2019-02-15 21:02:09:rastervision.backend.tf_object_detection: INFO - 2019-02-15 21:02:09.494358: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at conv_ops.cc:693 : Resource exhausted: OOM when allocating tensor with shape[32,256,128,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

2019-02-15 21:02:09:rastervision.backend.tf_object_detection: INFO - /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py:108: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.

2019-02-15 21:02:09:rastervision.backend.tf_object_detection: INFO -   "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "

2019-02-15 21:02:09:rastervision.backend.tf_object_detection: INFO - Traceback (most recent call last):

2019-02-15 21:02:09:rastervision.backend.tf_object_detection: INFO -   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1278, in _do_call

2019-02-15 21:02:09:rastervision.backend.tf_object_detection: INFO -     return fn(*args)

2019-02-15 21:02:09:rastervision.backend.tf_object_detection: INFO -   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1263, in _run_fn

2019-02-15 21:02:09:rastervision.backend.tf_object_detection: INFO -     options, feed_dict, fetch_list, target_list, run_metadata)

2019-02-15 21:02:09:rastervision.backend.tf_object_detection: INFO -   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun

2019-02-15 21:02:09:rastervision.backend.tf_object_detection: INFO -     run_metadata)

2019-02-15 21:02:09:rastervision.backend.tf_object_detection: INFO - tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,128,128,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

2019-02-15 21:02:09:rastervision.backend.tf_object_detection: INFO - 	 [[Node: FirstStageFeatureExtractor/resnet_v1_101/resnet_v1_101/block1/unit_1/bottleneck_v1/shortcut/Conv2D-0-1-TransposeNCHWToNHWC-LayoutOptimizer = Transpose[T=DT_FLOAT, Tperm=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](FirstStageFeatureExtractor/resnet_v1_101/resnet_v1_101/block1/unit_1/bottleneck_v1/shortcut/Conv2D, PermConstNCHWToNHWC-LayoutOptimizer)]]
WARNING:tensorflow:From /opt/tf-models/object_detection/predictors/heads/box_head.py:93: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
======================End of Report==========================
2019-02-15 21:02:32.216262: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-02-15 21:02:32.223360: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2019-02-15 21:02:32.223409: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: f73a16267948
2019-02-15 21:02:32.223418: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: f73a16267948
2019-02-15 21:02:32.223476: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 410.48.0
2019-02-15 21:02:32.223508: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 410.48.0
2019-02-15 21:02:32.223519: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 410.48.0

**Comment by lewfish** [comment]
I replied on Gitter:
The GTX 1050 doesn't have a lot of GPU RAM(2-3GB). Typically we use GPUs with 12-16 GB of GPU RAM. So I'm not surprised it only runs with a batch size of 2. As for using multiple GPUs with TF Object Detection API, we haven't done it before. There's probably some option you can pass, but I'm not aware of it. The old version which we used to use had a num_clones option https://github.com/tensorflow/models/blob/master/research/object_detection/legacy/train.py but it's not in the newer version. BTW, we are starting to experiment with swapping out the TF backends for new ones using PyTorch/Fast.ai which should be simpler, easier to tweak, and run faster.
