### ISSUE TITLE
rastervision.filesystem.filesystem.NotReadableError: Could not read 

### ISSUE THREAD

**Issue by busycalibrating** [azavea/raster-vision#693]
I've been running raster vision just fine for the past month or so, and then randomly this error started popping up whenever I try to run any experiment. I'm not convinced this is an actual raster vision issue (as opposed to a Windows issue) because I've been trying different model defaults, as well as reinstalling the raster vision library a couple of times. I'm wondering if anybody ran into this issue before and could give me some insight on some solutions? It looks like it doesn't even parse in the model defaults URI at the very bottom of the traceback. 

```
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\rastervision-script.py", line 11, in <module>
    load_entry_point('rastervision==0.8.0', 'console_scripts', 'rastervision')()
  File "C:\Anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\cli\main.py", line 138, in run
    experiments = loader.load_from_file(path)
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\experiment\experiment_loader.py", line 46, in load_from_file
    return self.load_from_module(name)
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\experiment\experiment_loader.py", line 54, in load_from_module
    result += self.load_from_set(experiment_set)
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\experiment\experiment_loader.py", line 58, in load_from_set
    return self.load_from_sets([experiment_set])
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\experiment\experiment_loader.py", line 81, in load_from_sets
    es = self.load_from_experiment(exp_func, full_name)
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\experiment\experiment_loader.py", line 112, in load_from_experiment
    exp = exp_func(**kwargs)
  File "C:\Users\Admin\Documents\Work\ml_pipeline\raster-vision-quickstart\local_tiny_spacenet.py", line 50, in exp_main
    .with_model_defaults(rv.MOBILENET_V2)  \
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\backend\backend_config.py", line 107, in with_model_defaults
    model_defaults = RVConfig.get_instance().get_model_defaults()
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\rv_config.py", line 203, in get_model_defaults
    model_defaults = json.loads(file_to_str(model_default_uri))
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\utils\files.py", line 216, in file_to_str
    return fs.read_str(uri)
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\filesystem\local_filesystem.py", line 48, in read_str
    raise NotReadableError('Could not read {}'.format(file_uri))
rastervision.filesystem.filesystem.NotReadableError: Could not read
```

**Comment by busycalibrating** [comment]
Figured it out... I was playing with some plugins and didn't properly clean up my ~/.rastervision/<plugins> files. Make sure to clean up unused files kids!
