### ISSUE TITLE
Trouble with single band raster source

### ISSUE THREAD

**Issue by busycalibrating** [azavea/raster-vision#700]
I'm trying to work with single band images right now, and I'm not totally clear on how to get things working nicely together. For what I'm trying to get working here, I'm just using the Quickstart code with DeepLab and a Semantic Segmentation task.

First, I set `channel_order = [0]`. Omitting this resulted in this error:
```bash
...
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\cli\main.py", line 253, in run_command
    rv.runner.CommandRunner.run(command_config_uri)
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\runner\command_runner.py", line 11, in run
    CommandRunner.run_from_proto(msg)
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\runner\command_runner.py", line 17, in run_from_proto
    command.run()
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\command\chip_command.py", line 22, in run
    map(lambda s: s.create_scene(cc.task, tmp_dir), cc.train_scenes))
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\command\chip_command.py", line 22, in <lambda>
    map(lambda s: s.create_scene(cc.task, tmp_dir), cc.train_scenes))
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\data\scene_config.py", line 36, in create_scene
    raster_source = self.raster_source.create_source(tmp_dir)
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\data\raster_source\geotiff_source_config.py", line 70, in create_source
    y_shift_meters=y_shift_meters)
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\data\raster_source\geotiff_source.py", line 46, in __init__
    super().__init__(raster_transformers, temp_dir, channel_order)
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\data\raster_source\rasterio_source.py", line 70, in __init__
    test_chip = transformer.transform(test_chip, channel_order)
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\data\raster_transformer\stats_transformer.py", line 59, in transform
    chip[nodata] = 0
IndexError: boolean index did not match indexed array along dimension 2; dimension is 0 but corresponding boolean dimension is 1
```

Running it through the chipping step yielded this error:

```bash
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\PIL\Image.py", line 2423, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 1), '|u1')

...

  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\backend\tf_deeplab.py", line 204, in create_tf_example
    image_encoded = numpy_to_png(image)
  File "C:\Anaconda3\lib\site-packages\rastervision-0.8.0-py3.6.egg\rastervision\utils\misc.py", line 32, in numpy_to_png
    im = Image.fromarray(array)
  File "C:\Anaconda3\lib\site-packages\PIL\Image.py", line 2426, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type
```

Looking at the PIL source code, the error arose from the a single channel image being fed into PIL as an array with shape `(1, 1, 1)` rather than `(1, 1)` (Verified by looking at the `typestr = KeyError: ((1, 1, 1), '|u1')`, and also the ). So to hack my way around this, I added the following to `rastervision/util/misc.py`:

```python
def numpy_to_png(array: np.ndarray) -> str:
    """Get a PNG string from a Numpy array.

    Args:
         array: A Numpy array of shape (w, h, 3) or (w, h), where the
               former is meant to become a three-channel image and the
               latter a one-channel image.  The dtype of the array
               should be uint8.

    Returns:
         str

    """
    #TODO: TEMPORARY WORKAROUND
    if len(array.shape) == 3:
        if array.shape[2] == 1:
            # print(array.shape)
            array = array.squeeze(axis=2)
            # print(array.shape)

    im = Image.fromarray(array)
    output = io.BytesIO()
    im.save(output, 'png')
    return output.getvalue()
```

which gave PIL the dimensions it expected. This allowed RV to generate the training/validation chips and spat them out as TFRecords, but then upon generating debug images from the `tf_deeplab` backend (calling `make_debug_images()`), it wants 3 channels to generate the PNGs. I've dug through a lot of the source code and didn't find something that handles single channel images in the form of a 2D array, (vs a `[n, m, 1]` array. Did I miss something or is this an oversight in the code?

**Comment by lewfish** [comment]
We've never tested things with a single channel scene. I think your fix for `numpy_to_png` makes sense.  Probably the easiest way to fix `make_debug_images` is to just take the one channel and then copy it three times to create an image with three channels. Unfortunately, `channel_order` needs to be of length 3 in order to use any pre-trained models` since they were trained on RGB.  If you want to be able to do this, then easiest workaround at this point is to just generate a new image with the channel copied 3 times and then use it instead of the original.

**Comment by busycalibrating** [comment]
Okay great to know I was on the right track, and that was what I figured I would have to do to get `make_debug_images` working. Thanks a lot for the input!

**Comment by lewfish** [comment]
After we switch over to using fastai/pytorch for the backends, we should be able to handle arbitrary numbers of channels. I'm leaving this open as a reminder to test things with a single channel image.

**Comment by ValRat** [comment]
@busycalibrating , I was also using a single band raster as a training source and setting `channel_order = [0, 0, 0]` seems to work ok. Not sure if this fits in with your use case however.

**Comment by lewfish** [comment]
> @busycalibrating , I was also using a single band raster as a training source and setting `channel_order = [0, 0, 0]` seems to work ok. Not sure if this fits in with your use case however.

If that works, that's an even better way of solving the problem!

**Comment by busycalibrating** [comment]
@ValRat Thanks for the tip, I'll give that a go! Not sure if it'll be the best solution for me as the images I will use might get big, but sounds like a nice quick workaround.
