### ISSUE TITLE
tiny_spacenet.py: AttributeError: module 'rastervision' has no attribute 'RASTERIZED_SOURCE'

### ISSUE THREAD

**Issue by hoonkai** [azavea/raster-vision#719]
I'm trying to run the `tiny_spacenet.py` example, but I keep getting the error:

```AttributeError: module 'rastervision' has no attribute 'RASTERIZED_SOURCE'```

Here's the trace:

```
root@1887e21d4fc9:/opt/src/code# rastervision run local -p tiny_spacenet.py
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/rastervision/__main__.py", line 17, in <module>
    rv.main()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/src/rastervision/cli/main.py", line 138, in run
    experiments = loader.load_from_file(path)
  File "/opt/src/rastervision/experiment/experiment_loader.py", line 46, in load_from_file
    return self.load_from_module(name)
  File "/opt/src/rastervision/experiment/experiment_loader.py", line 54, in load_from_module
    result += self.load_from_set(experiment_set)
  File "/opt/src/rastervision/experiment/experiment_loader.py", line 58, in load_from_set
    return self.load_from_sets([experiment_set])
  File "/opt/src/rastervision/experiment/experiment_loader.py", line 81, in load_from_sets
    es = self.load_from_experiment(exp_func, full_name)
  File "/opt/src/rastervision/experiment/experiment_loader.py", line 112, in load_from_experiment
    exp = exp_func(**kwargs)
  File "/opt/src/code/tiny_spacenet.py", line 42, in exp_main
    train_label_raster_source = rv.RasterSourceConfig.builder(rv.RASTERIZED_SOURCE) \
AttributeError: module 'rastervision' has no attribute 'RASTERIZED_SOURCE'
```

Is `rv.RASTERIZED_SOURCE` obsolete?

**Comment by lewfish** [comment]
The issue is that `RasterizedSource` was added after the 0.8 release, and I assume you're using 0.8. So you will need to use the `develop` branch or `-latest` Docker image.

**Comment by hoonkai** [comment]
Thanks!
