### ISSUE TITLE
Unable to use with_uris method to handle multiple uris

### ISSUE THREAD

**Issue by oluwayetty** [azavea/raster-vision#730]
The with_uris(uris) is used to Set URIs for a GeoTIFFs containing as raster data. After following the documentation, i am still unable to include multiple TIFF URIs. Has anyone been able to do this?

Including my a snippet of my code for review:

```
image_base_uri = os.listdir('images')
train_image_uri = [x for x in image_base_uri]

train_raster_source = rv.RasterSourceConfig.builder(rv.GEOTIFF_SOURCE) \
                                                   .with_uris(train_image_uri) \
                                                   .with_stats_transformer() \
                                                   .build()
```
And the error I get:

```
 File "/opt/src/rastervision/runner/experiment_runner.py", line 153, in run
    unique_commands, rerun_commands, skip_file_check=skip_file_check)
  File "/opt/src/rastervision/runner/command_dag.py", line 61, in __init__
    '\t{}\n'.format(',\b\t'.join(missing_files)))
rastervision.core.config.ConfigError: Files do not exist and are not supplied by commands:
```
Basically, I need a sample code that is using multiple TIF files from a **local directory** to train, not online.  The rastervision documentation displayed an experiment that trains with just one sample.

**Comment by lewfish** [comment]
That error means that RV can't find the files in `train_image_uris`. I would print out the value of `train_image_uris` and check that they are absolute paths that exist on the file system.

**Comment by oluwayetty** [comment]
Thanks @lewfish for your quick response. I have done all manners of debugging with no successful result, perhaps I'm missing something. 

For example, this works perfectly with no error, file path is in an array since I am using URIS.
`**.with_uris(['/opt/src/code/images/40.tif')** `

However, when I run something like: 
`**.with_uris(['/opt/src/code/images/40.tif', '/opt/src/code/images/45.tif'])** `

it doesn't work, notice the first line with one file works but the second gives me the error, because I'm attaching two files, or isn't multiple files allowed?:
```
ERROR 1: Failed to write .vrt file in FlushCache().
Traceback (most recent call last):
  File "rasterio/_base.pyx", line 199, in rasterio._base.DatasetBase.__init__
  File "rasterio/_shim.pyx", line 64, in rasterio._shim.open_dataset
  File "rasterio/_err.pyx", line 188, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_OpenFailedError: /tmp/tmp42f2uxdu/tmpzj8iq_98/index.vrt: No such file or directory

During handling of the above exception, another exception occurred:

 File "/usr/local/lib/python3.5/dist-packages/rasterio/__init__.py", line 217, in open
    s = DatasetReader(path, driver=driver, **kwargs)
  File "rasterio/_base.pyx", line 201, in rasterio._base.DatasetBase.__init__
rasterio.errors.RasterioIOError: /tmp/tmp42f2uxdu/tmpzj8iq_98/index.vrt: No such file or directory
/tmp/tmpjvog820c/tmp0vuzayd7/Makefile:6: recipe for target '0' failed
make: *** [0] Error 1
```

**Comment by lewfish** [comment]
You should be able to provide a list of URIs. Which version/commit of RV are you using? Did you do an `ls '/opt/src/code/images/45.tif` in the container where you are running RV?

**Comment by lewfish** [comment]
Also, just to clarify, you are trying to use multiple GeoTIFFs for a single scene right? (A scene is meant to cover a single contiguous area at a point in time).

**Comment by oluwayetty** [comment]
1. I'm using RV - 0.8.1, the latest one. 
2. The files definitely exist. Like I mentioned, any file i pick as a single file doesn't throw an error, error pops up when i try above 1.

Yes, you're right. I'm trying to use multiple GeoTIFFs for a single scene.

**Comment by lewfish** [comment]
I'm not experience this problem on the `master` branch. How are you running RV? If you are running the console from the [examples repo](https://github.com/azavea/raster-vision-examples), then you can run the latest changes by changing `0.8` to `latest` [here](https://github.com/azavea/raster-vision-examples/blob/master/scripts/build#L25) and [here](https://github.com/azavea/raster-vision-examples/blob/master/scripts/build#L36)

**Comment by lewfish** [comment]
I actually just merged the change I mentioned above to the `master` branch of the examples repo.

**Comment by oluwayetty** [comment]
`rastervision run local -p test.py` from the docker container is the command I use. Are you also passing a list of URIS in the `with_uris` method? Kindly share a snippet example since it works for you.
also, I'm not using the raster-vision-examples. i'm training with my own data.

**Comment by lewfish** [comment]
I don't have an easily sharable or understandable complete example for this. But what you are doing looks correct. You just need to use the `-latest` version of the Docker image and not `-0.8`. I think this is a bug that was fixed since that release.

**Comment by oluwayetty** [comment]
@lewfish thank you so much for your help, I switched to `-latest` and it seems I can now access the files but with a new error I can't even make sense of. 

```
2019-03-27 20:58:00:rastervision.data.raster_source.geotiff_source: INFO - Building VRT...
0...10...20...30...40...50...60...70...80...90...100 - done.
ERROR 1: Failed to write .vrt file in FlushCache().
Traceback (most recent call last):
  File "rasterio/_base.pyx", line 199, in rasterio._base.DatasetBase.__init__
  File "rasterio/_shim.pyx", line 64, in rasterio._shim.open_dataset
  File "rasterio/_err.pyx", line 188, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_OpenFailedError: /tmp/tmpt2jdes6_/tmp5bxu7udb/index.vrt: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/rastervision/__main__.py", line 17, in <module>
    rv.main()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/src/rastervision/cli/main.py", line 253, in run_command
    rv.runner.CommandRunner.run(command_config_uri)
  File "/opt/src/rastervision/runner/command_runner.py", line 11, in run
    CommandRunner.run_from_proto(msg)
  File "/opt/src/rastervision/runner/command_runner.py", line 17, in run_from_proto
    command.run()
  File "/opt/src/rastervision/command/analyze_command.py", line 18, in run
    map(lambda s: s.create_scene(cc.task, tmp_dir), cc.scenes))
  File "/opt/src/rastervision/command/analyze_command.py", line 18, in <lambda>
    map(lambda s: s.create_scene(cc.task, tmp_dir), cc.scenes))
  File "/opt/src/rastervision/data/scene_config.py", line 36, in create_scene
    raster_source = self.raster_source.create_source(tmp_dir)
  File "/opt/src/rastervision/data/raster_source/geotiff_source_config.py", line 70, in create_source
    y_shift_meters=y_shift_meters)
  File "/opt/src/rastervision/data/raster_source/geotiff_source.py", line 46, in __init__
    super().__init__(raster_transformers, temp_dir, channel_order)
  File "/opt/src/rastervision/data/raster_source/rasterio_source.py", line 46, in __init__
    with self.activate():
  File "/opt/src/rastervision/data/activate_mixin.py", line 21, in __enter__
    self.activate()
  File "/opt/src/rastervision/data/activate_mixin.py", line 54, in do_activate
    self._activate()
  File "/opt/src/rastervision/data/raster_source/geotiff_source.py", line 104, in _activate
    super()._activate()
  File "/opt/src/rastervision/data/raster_source/rasterio_source.py", line 101, in _activate
    self.image_dataset = rasterio.open(self.imagery_path)
  File "/usr/local/lib/python3.5/dist-packages/rasterio/env.py", line 402, in wrapper
    return f(*args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/rasterio/__init__.py", line 217, in open
    s = DatasetReader(path, driver=driver, **kwargs)
  File "rasterio/_base.pyx", line 201, in rasterio._base.DatasetBase.__init__
rasterio.errors.RasterioIOError: /tmp/tmpt2jdes6_/tmp5bxu7udb/index.vrt: No such file or directory
/tmp/tmpgj9dyksw/tmpl9y93c4h/Makefile:6: recipe for target '0' failed
make: *** [0] Error 1
```

**Comment by lewfish** [comment]
Did you get this to work? I just realized this could happen if you are passing a list of non-georeferenced TIFFs. In any case, it seems to have something to do with the images you are using. If you could send a sample that could help me debug it.

**Comment by oluwayetty** [comment]
I actually couldn't get it to work. I eventually had to manually use gdal to generate my vrt and then passed the vrt file path into my code since the generation of the vrt for the images failed. Between, the  TIFFs images are georeferenced so I'm not sure why the vrt generation was failing.
