### ISSUE TITLE
Error on chipping task when using gpu:0.9 image

### ISSUE THREAD

**Issue by ljvmiranda921** [azavea/raster-vision#772]
Hi, I encountered an error when chipping. I can't seem to debug why the error is happening. Any ideas? @lewfish 

```python-traceback
2019-04-25 09:19:08:rastervision.task.task: INFO - Making train chips for scene: train-250
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/rastervision/__main__.py", line 17, in <module>
    rv.main()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/src/rastervision/cli/main.py", line 292, in run_command
    rv.runner.CommandRunner.run(command_config_uri)
  File "/opt/src/rastervision/runner/command_runner.py", line 11, in run
    CommandRunner.run_from_proto(msg)
  File "/opt/src/rastervision/runner/command_runner.py", line 17, in run_from_proto
    command.run()
  File "/opt/src/rastervision/command/chip_command.py", line 29, in run
    task.make_chips(train_scenes, val_scenes, augmentors, tmp_dir)
  File "/opt/src/rastervision/task/task.py", line 128, in make_chips
    train_scenes, TRAIN, augment=True)
  File "/opt/src/rastervision/task/task.py", line 124, in _process_scenes
    return [_process_scene(scene, type_, augment) for scene in scenes]
  File "/opt/src/rastervision/task/task.py", line 124, in <listcomp>
    return [_process_scene(scene, type_, augment) for scene in scenes]
  File "/opt/src/rastervision/task/task.py", line 107, in _process_scene
    windows = self.get_train_windows(scene)
  File "/opt/src/rastervision/task/object_detection.py", line 107, in get_train_windows
    self.config.chip_options.label_buffer))
  File "/opt/src/rastervision/task/object_detection.py", line 58, in make_pos_windows
    return _make_chip_pos_windows(image_extent, label_store, chip_size)
  File "/opt/src/rastervision/task/object_detection.py", line 28, in _make_chip_pos_windows
    window = box.make_random_square_container(chip_size)
  File "/opt/src/rastervision/core/box.py", line 117, in make_random_square_container
    rand_y = random.randint(lb, ub)
  File "/usr/lib/python3.5/random.py", line 218, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.5/random.py", line 191, in randrange
    raise ValueError("non-integer stop for randrange()")
ValueError: non-integer stop for randrange()
/tmp/tmpm06f3lz1/tmpria8hf54/Makefile:9: recipe for target '1' failed
make: *** [1] Error 1
```

**Comment by lewfish** [comment]
Someone in the Gitter channel had the same problem. I'm not sure what's causing that, so I would need to check out the scene with id `train-250`. If you take a look at the imagery and labels for that scene, you might realize what the problem is. Or if you could send me the data, I could try to debug it.

**Comment by ljvmiranda921** [comment]
Hi @lewfish , turns out the problem in my dataset is that I have labels (in `.geojson`) that are `MultiPolygons`. Upon removing those samples with `MultiPolygons`, the whole chipping process worked!

You can close this issue now whenever you please

**Comment by lewfish** [comment]
Actually, RV should be able to handle `MultiPolygons` now, so this seems like a bug I could and should fix. If you send me a sample of the GeoJSON that caused the problem I could test it.
