### ISSUE TITLE
QGIS Plugin Error after Installation

### ISSUE THREAD

**Issue by toren77** [azavea/raster-vision#780]
Hi

QGIS Plugin installed on QGIS 3.6.2-Noosa 
Operating System : Ubuntu 18.04
raster-vision installed with : python3 -m pip install rasterviosion  
raster-vision version is : rastervision-0.8.1-py3-none-any

Immediately after  plugin installation got errors:

2019-05-12T09:50:21     WARNING    Traceback (most recent call last):
              File "/home/sunnyside/.local/share/QGIS/QGIS3/profiles/default/python/plugins/rastervision_qgis/raster_vision.py", line 208, in run_load_experiment
              self.experiment_controller.run()
              File "/home/sunnyside/.local/share/QGIS/QGIS3/profiles/default/python/plugins/rastervision_qgis/experiment_dialog.py", line 161, in run
              experiment = self.dlg.experiment
             AttributeError: 'ExperimentDialog' object has no attribute 'experiment'
             
2019-05-12T09:50:21     WARNING    Traceback (most recent call last):
              File "/home/sunnyside/.local/share/QGIS/QGIS3/profiles/default/python/plugins/rastervision_qgis/raster_vision.py", line 208, in run_load_experiment
              self.experiment_controller.run()
              File "/home/sunnyside/.local/share/QGIS/QGIS3/profiles/default/python/plugins/rastervision_qgis/experiment_dialog.py", line 161, in run
              experiment = self.dlg.experiment
             AttributeError: 'ExperimentDialog' object has no attribute 'experiment'
             
2019-05-12T09:50:21     WARNING    Traceback (most recent call last):
              File "/home/xxx/.local/share/QGIS/QGIS3/profiles/default/python/plugins/rastervision_qgis/raster_vision.py", line 208, in run_load_experiment
              self.experiment_controller.run()
              File "/home/xxx/.local/share/QGIS/QGIS3/profiles/default/python/plugins/rastervision_qgis/experiment_dialog.py", line 161, in run
              experiment = self.dlg.experiment
             AttributeError: 'ExperimentDialog' object has no attribute 'experiment'

**Comment by lossyrob** [comment]
Hi @toren77, sorry for the delayed response - we've been having trouble getting the QGIS plugin working on different environments - it turns out to be very finicky based on what system it's installed in (something we use docker containers to abstract over when we don't need a UI). Please bear with us as we're making assessments about the supportability of the plugin moving forward.

If there's something specific you're trying to do with it, let us know and we can strategize a workaround. Thanks!

**Comment by lewfish** [comment]
I'm closing this since the QGIS plugin has been discontinued.
