### ISSUE TITLE
Ensemble run error

### ISSUE THREAD

**Issue by DaDaPi3** [azavea/raster-vision#80]
I was trying to run an ensemble experiment and got the following error. "load_options" is missing. Can somebody please help?

Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/rastervision/run.py", line 47, in <module>
    run_tasks()
  File "/opt/src/rastervision/run.py", line 37, in run_tasks
    runner.run_tasks(options, args.tasks)
  File "/opt/src/rastervision/common/run.py", line 67, in run_tasks
    self.run_path, self.options, self.generator, use_best=True)
  File "/opt/src/rastervision/common/models/factory.py", line 40, in get_model
    model = self.make_model(options, generator)
  File "/opt/src/rastervision/semseg/models/factory.py", line 88, in make_model
    models, active_input_inds_list = self.load_ensemble_models(options)
  File "/opt/src/rastervision/semseg/models/factory.py", line 28, in load_ensemble_models
    from ..options import load_options
ImportError: cannot import name 'load_options'

**Comment by DaDaPi3** [comment]
Found in the commit from Apr. 6.
