### ISSUE TITLE
"envs\raster_vision\lib\subprocess.py", line 1178, in _execute_child     startupinfo) FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by hugonbgg** [azavea/raster-vision#805]
I am following the quickstart tutorial: https://docs.rastervision.io/en/0.9/quickstart.html
And I was able to execute everything but the last line.
"When we’re ready to run, we just remove the -n flag:"

But when I run:
rastervision run local -p tiny_spacenet.py
the following error is displayed:

(raster_vision) C:\Users\Hugo\raster_vision>rastervision -vv run local -p tiny_spacenet.py
2019-07-17 02:29:24:rastervision.runner.experiment_runner: DEBUG - Generating command definitions from experiments...
2019-07-17 02:29:24:rastervision.runner.command_definition: DEBUG - Generating command definitions for experiment tiny-spacenet-experiment...
2019-07-17 02:29:24:rastervision.runner.command_definition: DEBUG - Updating config for command ANALYZE...
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating task for command ANALYZE
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating backend for command ANALYZE
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating dataset for command ANALYZE
2019-07-17 02:29:24:rastervision.data.dataset_config: DEBUG - Updating train scenes for command ANALYZE
Updating train scenes  [####################################]  100%
2019-07-17 02:29:24:rastervision.data.dataset_config: DEBUG - Updating validation scenes for command ANALYZE
Updating validation scenes...    [####################################]  100%
2019-07-17 02:29:24:rastervision.data.dataset_config: DEBUG - Updating test scenes for command ANALYZE
Updating test scenes...    [####################################]  100%
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating analyzers for command ANALYZE
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating evaluators for command ANALYZE
2019-07-17 02:29:24:rastervision.runner.command_definition: DEBUG - Creating command configurations for ANALYZE...
2019-07-17 02:29:24:rastervision.runner.command_definition: DEBUG - Updating config for command CHIP...
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating task for command CHIP
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating backend for command CHIP
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating dataset for command CHIP
2019-07-17 02:29:24:rastervision.data.dataset_config: DEBUG - Updating train scenes for command CHIP
Updating train scenes  [####################################]  100%
2019-07-17 02:29:24:rastervision.data.dataset_config: DEBUG - Updating validation scenes for command CHIP
Updating validation scenes...    [####################################]  100%
2019-07-17 02:29:24:rastervision.data.dataset_config: DEBUG - Updating augmentors for command CHIP
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating analyzers for command CHIP
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating evaluators for command CHIP
2019-07-17 02:29:24:rastervision.runner.command_definition: DEBUG - Creating command configurations for CHIP...
2019-07-17 02:29:24:rastervision.runner.command_definition: DEBUG - Updating config for command TRAIN...
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating task for command TRAIN
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating backend for command TRAIN
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating dataset for command TRAIN
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating analyzers for command TRAIN
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating evaluators for command TRAIN
2019-07-17 02:29:24:rastervision.runner.command_definition: DEBUG - Creating command configurations for TRAIN...
2019-07-17 02:29:24:rastervision.runner.command_definition: DEBUG - Updating config for command PREDICT...
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating task for command PREDICT
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating backend for command PREDICT
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating dataset for command PREDICT
2019-07-17 02:29:24:rastervision.data.dataset_config: DEBUG - Updating validation scenes for command PREDICT
Updating validation scenes...    [####################################]  100%
2019-07-17 02:29:24:rastervision.data.dataset_config: DEBUG - Updating test scenes for command PREDICT
Updating test scenes...    [####################################]  100%
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating analyzers for command PREDICT
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating evaluators for command PREDICT
2019-07-17 02:29:24:rastervision.runner.command_definition: DEBUG - Creating command configurations for PREDICT...
2019-07-17 02:29:24:rastervision.runner.command_definition: DEBUG - Updating config for command EVAL...
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating task for command EVAL
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating backend for command EVAL
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating dataset for command EVAL
2019-07-17 02:29:24:rastervision.data.dataset_config: DEBUG - Updating validation scenes for command EVAL
Updating validation scenes...    [####################################]  100%
2019-07-17 02:29:24:rastervision.data.dataset_config: DEBUG - Updating test scenes for command EVAL
Updating test scenes...    [####################################]  100%
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating analyzers for command EVAL
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating evaluators for command EVAL
2019-07-17 02:29:24:rastervision.runner.command_definition: DEBUG - Creating command configurations for EVAL...
2019-07-17 02:29:24:rastervision.runner.command_definition: DEBUG - Updating config for command BUNDLE...
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating task for command BUNDLE
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating backend for command BUNDLE
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating dataset for command BUNDLE
2019-07-17 02:29:24:rastervision.data.dataset_config: DEBUG - Updating validation scenes for command BUNDLE
Updating validation scenes...    [####################################]  100%
2019-07-17 02:29:24:rastervision.data.dataset_config: DEBUG - Updating test scenes for command BUNDLE
Updating test scenes...    [####################################]  100%
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating analyzers for command BUNDLE
2019-07-17 02:29:24:rastervision.experiment.experiment_config: DEBUG - Updating evaluators for command BUNDLE
2019-07-17 02:29:24:rastervision.runner.command_definition: DEBUG - Creating command configurations for BUNDLE...
2019-07-17 02:29:24:rastervision.runner.experiment_runner: DEBUG - Filtering commands that do not have any output...
2019-07-17 02:29:24:rastervision.runner.experiment_runner: DEBUG - Checking for missing input from configuration...
2019-07-17 02:29:24:rastervision.runner.experiment_runner: DEBUG - Removing duplicate commands...
2019-07-17 02:29:24:rastervision.runner.experiment_runner: DEBUG - Ensuring commands do not overwrite each other's outputs...
2019-07-17 02:29:24:rastervision.runner.experiment_runner: DEBUG - Constructing command DAG...
2019-07-17 02:29:24:rastervision.runner.command_dag: DEBUG - Creating command and URI DAG from command definitions...
2019-07-17 02:29:24:rastervision.runner.command_dag: DEBUG - Ensuring input files exist...
Ensuring input files exist    [####################################]  100%
2019-07-17 02:29:26:rastervision.runner.command_dag: DEBUG - Checking for existing output...
Checking for existing output  [####################################]  100%
2019-07-17 02:29:26:rastervision.runner.command_dag: DEBUG - Creating DAG of commands...
2019-07-17 02:29:26:rastervision.runner.experiment_runner: DEBUG - Saving experiment configuration for experiment tiny-spacenet-experiment
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating task for command ANALYZE
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating backend for command ANALYZE
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating dataset for command ANALYZE
2019-07-17 02:29:26:rastervision.data.dataset_config: DEBUG - Updating train scenes for command ANALYZE
Updating train scenes  [####################################]  100%
2019-07-17 02:29:26:rastervision.data.dataset_config: DEBUG - Updating validation scenes for command ANALYZE
Updating validation scenes...    [####################################]  100%
2019-07-17 02:29:26:rastervision.data.dataset_config: DEBUG - Updating test scenes for command ANALYZE
Updating test scenes...    [####################################]  100%
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating analyzers for command ANALYZE
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating evaluators for command ANALYZE
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating task for command CHIP
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating backend for command CHIP
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating dataset for command CHIP
2019-07-17 02:29:26:rastervision.data.dataset_config: DEBUG - Updating train scenes for command CHIP
Updating train scenes  [####################################]  100%
2019-07-17 02:29:26:rastervision.data.dataset_config: DEBUG - Updating validation scenes for command CHIP
Updating validation scenes...    [####################################]  100%
2019-07-17 02:29:26:rastervision.data.dataset_config: DEBUG - Updating augmentors for command CHIP
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating analyzers for command CHIP
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating evaluators for command CHIP
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating task for command TRAIN
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating backend for command TRAIN
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating dataset for command TRAIN
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating analyzers for command TRAIN
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating evaluators for command TRAIN
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating task for command PREDICT
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating backend for command PREDICT
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating dataset for command PREDICT
2019-07-17 02:29:26:rastervision.data.dataset_config: DEBUG - Updating validation scenes for command PREDICT
Updating validation scenes...    [####################################]  100%
2019-07-17 02:29:26:rastervision.data.dataset_config: DEBUG - Updating test scenes for command PREDICT
Updating test scenes...    [####################################]  100%
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating analyzers for command PREDICT
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating evaluators for command PREDICT
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating task for command EVAL
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating backend for command EVAL
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating dataset for command EVAL
2019-07-17 02:29:26:rastervision.data.dataset_config: DEBUG - Updating validation scenes for command EVAL
Updating validation scenes...    [####################################]  100%
2019-07-17 02:29:26:rastervision.data.dataset_config: DEBUG - Updating test scenes for command EVAL
Updating test scenes...    [####################################]  100%
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating analyzers for command EVAL
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating evaluators for command EVAL
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating task for command BUNDLE
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating backend for command BUNDLE
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating dataset for command BUNDLE
2019-07-17 02:29:26:rastervision.data.dataset_config: DEBUG - Updating validation scenes for command BUNDLE
Updating validation scenes...    [####################################]  100%
2019-07-17 02:29:26:rastervision.data.dataset_config: DEBUG - Updating test scenes for command BUNDLE
Updating test scenes...    [####################################]  100%
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating analyzers for command BUNDLE
2019-07-17 02:29:26:rastervision.experiment.experiment_config: DEBUG - Updating evaluators for command BUNDLE
2019-07-17 02:29:26:rastervision.runner.experiment_runner: DEBUG - Running experiment...
2019-07-17 02:29:26:rastervision.rv_config: DEBUG - Temporary directory is: C:\Users\Hugo\AppData\Local\Temp
Saving command configuration to C:/Users/Hugo/raster_vision/rv\analyze\tiny-spacenet-experiment\command-config-0.json...
Saving command configuration to C:/Users/Hugo/raster_vision/rv\chip\tiny-spacenet-experiment\command-config-0.json...
Saving command configuration to C:/Users/Hugo/raster_vision/rv\train\tiny-spacenet-experiment\command-config-0.json...
Saving command configuration to C:/Users/Hugo/raster_vision/rv\bundle\tiny-spacenet-experiment\command-config-0.json...
Saving command configuration to C:/Users/Hugo/raster_vision/rv\predict\tiny-spacenet-experiment\command-config-0.json...
Saving command configuration to C:/Users/Hugo/raster_vision/rv\eval\tiny-spacenet-experiment\command-config-0.json...
Traceback (most recent call last):
  File "c:\users\hugo\anaconda3\envs\raster_vision\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\hugo\anaconda3\envs\raster_vision\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Hugo\Anaconda3\envs\raster_vision\Scripts\rastervision.exe\__main__.py", line 9, in <module>
  File "c:\users\hugo\anaconda3\envs\raster_vision\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\hugo\anaconda3\envs\raster_vision\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\hugo\anaconda3\envs\raster_vision\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\hugo\anaconda3\envs\raster_vision\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\hugo\anaconda3\envs\raster_vision\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\hugo\anaconda3\envs\raster_vision\lib\site-packages\rastervision\cli\main.py", line 166, in run
    splits=splits)
  File "c:\users\hugo\anaconda3\envs\raster_vision\lib\site-packages\rastervision\runner\experiment_runner.py", line 190, in run
    self._run_experiment(command_dag)
  File "c:\users\hugo\anaconda3\envs\raster_vision\lib\site-packages\rastervision\runner\local_experiment_runner.py", line 63, in _run_experiment
    process = Popen(['make', '-j', '-f', makefile_name])
  File "c:\users\hugo\anaconda3\envs\raster_vision\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\hugo\anaconda3\envs\raster_vision\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado

(raster_vision) C:\Users\Hugo\raster_vision>

**Comment by lewfish** [comment]
I think this is because Raster Vision is trying to call `make` and it isn't installed. We're assuming that `make` is already available because it's running in a Unix-like environment. We don't support running RV directly in Windows. For now the best option is to run it from within Docker.

**Comment by jamesmcclain** [comment]
@hugonbg Yes, it looks as though it is failing because `make` is not installed.  The [minGW version of GNU make for Windows](http://www.mingw.org/wiki/make) should work, but has never been tested.
