### ISSUE TITLE
StatsTransformer apparently causing S3 URIs to be lost

### ISSUE THREAD

**Issue by moradology** [azavea/raster-vision#966]
Use of the `StatsTransformer` within `rv_stac_config.py` in [this PR](https://github.com/azavea/noaa-flood-mapping/pull/47) led to a situation in which a URI of `None` was being passed through to VSI path generation. Removing the `StatsTransformer`s from this code allowed the S3 filesystem code to work as expected

**Comment by lewfish** [comment]
Could you please provide the command invoked and full output to aid troubleshooting?

**Comment by moradology** [comment]
I should've captured this information when I initially saw the behavior as multiple things have changed since and I'm now having trouble reproducing it. Perhaps there was some simple misconfiguration that has since been fixed. I'll add stdout from the run that ran into trouble close this issue for now.
```
root@31f3d26af65b:/opt/src# rastervision run local code/noaa_stac_config.py
python -m rastervision.pipeline.cli run_command /opt/data/output/pipeline-config.json analyze
Running analyze command...
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 233, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 225, in run_command
    runner=runner)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 202, in _run_command
    command_fn()
  File "/opt/src/rastervision_core/rastervision/core/rv_pipeline/rv_pipeline.py", line 51, in analyze
    for s in self.config.dataset.train_scenes
  File "/opt/src/rastervision_core/rastervision/core/rv_pipeline/rv_pipeline.py", line 51, in <listcomp>
    for s in self.config.dataset.train_scenes
  File "/opt/src/rastervision_core/rastervision/core/data/scene_config.py", line 35, in build
    if self.label_source is not None else None)
  File "/opt/src/rastervision_core/rastervision/core/data/label_source/semantic_segmentation_label_source_config.py", line 27, in build
    rs = self.raster_source.build(tmp_dir)
  File "/opt/src/rastervision_core/rastervision/core/data/raster_source/rasterio_source_config.py", line 28, in build
    if use_transformers else [])
  File "/opt/src/rastervision_core/rastervision/core/data/raster_source/rasterio_source_config.py", line 27, in <listcomp>
    raster_transformers = ([rt.build() for rt in self.transformers]
  File "/opt/src/rastervision_core/rastervision/core/data/raster_transformer/stats_transformer_config.py", line 25, in build
    return StatsTransformer(RasterStats.load(self.stats_uri))
  File "/opt/src/rastervision_core/rastervision/core/raster_stats.py", line 147, in load
    stats_json = json.loads(file_to_str(stats_uri))
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/file_system/utils.py", line 262, in file_to_str
    fs = FileSystem.get_file_system(uri, 'r')
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/file_system/file_system.py", line 32, in get_file_system
    return registry.get_file_system(uri, mode)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/registry.py", line 128, in get_file_system
    if fs.matches_uri(uri, mode):
  File "/opt/src/rastervision_gdal_vsi/rastervision/gdal_vsi/vsi_file_system.py", line 62, in matches_uri
    if mode == 'r' and vsipath.startswith('/vsi'):
AttributeError: 'NoneType' object has no attribute 'startswith'
/opt/data/output/Makefile:6: recipe for target '0' failed
```
