### ISSUE TITLE
Improve error messages when classes in labels are invalid

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#969]
If a `LabelSource` returns labels with `class_ids` that are not in [0, num_classes), then we should raise an error with a descriptive message as soon as possible. Currently, the error is raised by PyTorch during the training stage and which is difficult for users to interpret. An example is below:

```
Running train command...
2020-08-04 20:49:20:rastervision.pytorch_learner.learner: INFO - model=SemanticSegmentationModelConfig(backbone=<Backbone.resnet50: 'resnet50'>, pretrained=True, init_weights=None, type_hint='semantic_segmentation_model') solver=SolverConfig(lr=0.0001, num_epochs=1, test_num_epochs=2, test_batch_sz=4, overfit_num_steps=1, sync_interval=1, batch_sz=2, one_cycle=True, multi_stage=[], type_hint='solver') data=SemanticSegmentationDataConfig(uri='/opt/data/output/chip', train_sz=None, group_uris=None, group_train_sz=None, data_format=<SemanticSegmentationDataFormat.default: 'default'>, class_names=['no data', 'not water', 'water', 'null'], class_colors=['black', 'white', 'blue', 'black'], img_sz=300, num_workers=4, augmentors=['RandomRotate90', 'HorizontalFlip', 'VerticalFlip'], type_hint='semantic_segmentation_data') predict_mode=False test_mode=False overfit_mode=False eval_train=False save_model_bundle=True log_tensorboard=True run_tensorboard=False output_uri='/opt/data/output/train' type_hint='semantic_segmentation_learner'
2020-08-04 20:49:20:rastervision.pytorch_learner.learner: INFO - train_ds: 20 items
2020-08-04 20:49:20:rastervision.pytorch_learner.learner: INFO - valid_ds: 90 items
2020-08-04 20:49:20:rastervision.pytorch_learner.learner: INFO - test_ds: 90 items
2020-08-04 20:49:21:rastervision.pytorch_learner.learner: INFO - epoch: 0
Training  [###---------------------------------]   10%
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 233, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 225, in run_command
    runner=runner)
  File "/opt/src/rastervision_pipeline/rastervision/pipeline/cli.py", line 202, in _run_command
    command_fn()
  File "/opt/src/rastervision_core/rastervision/core/rv_pipeline/rv_pipeline.py", line 114, in train
    backend.train()
  File "/opt/src/rastervision_pytorch_backend/rastervision/pytorch_backend/pytorch_learner_backend.py", line 69, in train
    learner.main()
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner.py", line 152, in main
    self.train()
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner.py", line 864, in train
    train_metrics = self.train_epoch()
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/learner.py", line 795, in train_epoch
    output = self.train_step(batch, batch_ind)
  File "/opt/src/rastervision_pytorch_learner/rastervision/pytorch_learner/semantic_segmentation_learner.py", line 100, in train_step
    return {'train_loss': F.cross_entropy(out, y)}
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 1995, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 1826, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Assertion `cur_target >= 0 && cur_target < n_classes' failed.  at /pytorch/aten/src/THNN/generic/SpatialClassNLLCriterion.c:111
/opt/data/output/Makefile:12: recipe for target '2' failed
```

**Comment by nr1040gh** [comment]
Hi @lewfish , I am new to RasterVision and machine learning in general and I am trying to follow one of your examples for semantic segmentation with raster labels (https://github.com/azavea/raster-vision/blob/0.12/rastervision_pytorch_backend/rastervision/pytorch_backend/examples/semantic_segmentation/isprs_potsdam.py). However, I am instead using data I found. My images are RGB .tif's and the labels are corresponding RGB .tif ground truth where the buildings are red (255,0,0) and everything else is blue (0,0,255). I have included my code down below. When I run this, it crashes right at the train command and I receive the exact same error you have posted above. I have been trying to remedy this with no success - if my LabelSource returns labels with class_ids that are not in [0, num_classes), is there anyway to see what they are returning and or what the interval [0, num_classes) is?

Thank you



`import` os

from os.path import join

from rastervision.core.rv_pipeline import *
from rastervision.core.backend import *
from rastervision.core.data import *
from rastervision.pytorch_backend import *
from rastervision.pytorch_learner import *

def get_config(runner):
	root_uri = '/opt/data/output'

	base_test_uri = '/opt/data/Dataset/test/images'
	base_train_uri = '/opt/data/Dataset/train'
	gt_uri = base_train_uri + '/gtRB' #ground truth folder, contains .tif files
	images_uri = base_train_uri + '/images' #Images corresponding to ground truth, contains .tif files

	gtlabel_image1 = gt_uri + '/gttrainlabel_RB.tif'
	image1 = images_uri + '/trainimage1.tif'

	gtlabel_image2 = gt_uri + '/gtvallabel_RB.tif'
	image2 = images_uri + '/valimage.tif'

	
	'''
	class_config = ClassConfig(names=['background','building','blank'],
								colors=['#0000ff','#ff0000','#00ff00'],null_class='blank')
	'''
	class_config = ClassConfig(names=['building','blank'],
								colors=['#ff0000','#0000ff'],null_class='blank')

	
	def make_scene(scene_id,image_uri,label_uri,root_uri):
		channel_order = [0,1,2]
		raster_source = RasterioSourceConfig(channel_order=channel_order,
											uris=[image_uri]
											)
		label_source = SemanticSegmentationLabelSourceConfig(
            rgb_class_config=class_config,
            raster_source=RasterioSourceConfig(uris=[label_uri],channel_order=channel_order))


		#label_store = SemanticSegmentationLabelStoreConfig(rgb=True, vector_output=[PolygonVectorOutputConfig(class_id=1)])

		return SceneConfig(id=scene_id,
							raster_source=raster_source,
							label_source=label_source)
							#label_store=label_store) 

	dataset = DatasetConfig(class_config=class_config,
							train_scenes=[
							make_scene('train',image1,gtlabel_image1,root_uri)
							],
							validation_scenes=[
							make_scene('val',image2,gtlabel_image2,root_uri)
							])

	chip_sz = 300 #300 This should reduce number of chips for a scene if using the default window method which is sliding
	backend = PyTorchSemanticSegmentationConfig(
				model = SemanticSegmentationModelConfig(),
				solver = SolverConfig(lr=1e-4,num_epochs=1, batch_sz=3)
				)
	chip_options = SemanticSegmentationChipOptions(window_method=SemanticSegmentationWindowMethod.random_sample,
		chips_per_scene=10) #10 #CHIPS_PER_SCENE only works with random_sample method for window_method, use random_sample for quick prototyping?

	return SemanticSegmentationConfig(root_uri=root_uri,dataset=dataset,backend=backend,train_chip_sz=chip_sz,predict_chip_sz=chip_sz,chip_options=chip_options)`
